### ISSUE TITLE
mpp_slots_set_prop error with vpu hardware decoder

### ISSUE THREAD

**Issue by geekerlw** [rockchip-linux/mpp#1]
I just found your gstreamer-rockchip plugin may not work without h264parse, when I debug the gstreamer programs, each time I played the video , the error blow printed:  
### mpp_buf_slot: mpp_slots_set_prop found invalid input slots 0xa78822a0 type 3 val (nil)  
   I don't know how to debug gstreamer with mpp, and I'll give the current log I got here:  
   With the --gst-debug=vpudec:5,vpubufferpool:5,h264parse:5 , I got the debug log as blow:  
   one is normal when the video switched: http://paste.fedoraproject.org/525878/41931441/  
   another is stoped playing at the last frame 239: http://paste.fedoraproject.org/525879/14841932/  
   The video is looped again and again, and It's 239 frames, I don't know why it didn't got an eos message at the last frame?

**Comment by hizukiayaka** [comment]
It is just a warning message, harmless.
