### ISSUE TITLE
mpi_dec_test没有报错，也没有数据反馈

### ISSUE THREAD

**Issue by lindefoe** [rockchip-linux/mpp#107]
rk3399_firefly_aio_lvds_box:/ # mpi_dec_test                                                                                                        
1|rk3399_firefly_aio_lvds_box:/ # mpi_dec_test                                                                                                        
1|rk3399_firefly_aio_lvds_box:/ # 

如上面内容显示，可执行文件没有返回有效数据
板子烧录的系统是安卓7.1.1，内核信息：Linux localhost 4.4.83 #1 SMP PREEMPT Thu Jul 18 21:48:56 CST 2019 aarch64
mpi_dec_test程序信息：test/mpi_dec_test: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/, not stripped
libmpp.so和libvpu.so信息：file format elf64-littleaarch64
库推到了/system/lib64,可执行文件在/system/bin中

改了使用mpp-release/build/android/aarch64的make-Android.bash编译并make

改后的内容如下

#!/bin/bash
Run this from within a bash shell

HOST_IP=hostname --all-ip-addresses
if [ ${HOST_IP} == "10.10.10.65" ] || [ ${HOST_IP} == "10.10.10.67" ]; then
ANDROID_NDK=/home/lancoo/EnvAndroid/NDK/android-ndk-r14b/
else
ANDROID_NDK=/home/lancoo/EnvAndroid/NDK/android-ndk-r14b/
fi

PLATFORM=$ANDROID_NDK/platforms/android-24/arch-arm64

cmake -DCMAKE_TOOLCHAIN_FILE=../android.toolchain.cmake
-DCMAKE_BUILD_TYPE=Release
-DANDROID_FORCE_ARM_BUILD=ON
-DANDROID_NDK=${ANDROID_NDK}
-DANDROID_SYSROOT=${PLATFORM}
-DANDROID_ABI="arm64-v8a"
-DANDROID_TOOLCHAIN_NAME="aarch64-linux-android-4.9"
-DANDROID_NATIVE_API_LEVEL=android-24
-DANDROID_STL=system
-DRKPLATFORM=ON
-DHAVE_DRM=ON
../../../

  #-DCMAKE_BUILD_TYPE=Debug                                              \
  #-DCMAKE_VERBOSE_MAKEFILE=true                                         \
  #--trace                                                               \
  #--debug-output                                                        \

#cmake --build . --clean-first -- V=1
cmake --build .

#adb push osal/test/rk_log_test /system/bin/
#adb push osal/test/rk_thread_test /system/bin/
#adb shell sync
#adb shell logcat -c
#adb shell rk_log_test
#adb shell `rk_thread_test`

**Comment by Nian8113** [comment]
請教一下，
要怎麼正確地把mpi_dec_test push到平台上，
我要執行一直返回"can't execute: Permission denied"。
