### ISSUE TITLE
MPP_DEC_SET_OUTPUT_FORMAT没有效果？

### ISSUE THREAD

**Issue by lwdddddddd** [rockchip-linux/mpp#109]
你好，请问如果mpi->control(ctx, MPP_DEC_SET_OUTPUT_FORMAT, &my_format);是用来设置解码输出格式的话，为什么我设置为格式为MPP_FMT_ARGB8888，输出的确任然是NV12呢？

**Comment by lwdddddddd** [comment]
你好，请问如果mpi->control(ctx, MPP_DEC_SET_OUTPUT_FORMAT, &my_format);是用来设置解码输出格式的话，为什么我设置格式为MPP_FMT_ARGB8888，输出的却仍然是NV12呢？

**Comment by HermanChen** [comment]
SET_OUTPUT_FORMAT 只对 jpeg 解码有用，对其他格式的解码无效

**Comment by lwdddddddd** [comment]
好的，谢谢。
