### ISSUE TITLE
RK3399: rockchip-linux/mpp on Android8.1

### ISSUE THREAD

**Issue by santo4ul** [rockchip-linux/mpp#114]
Hi, 

**Platform:** RK3399
**OS:** Android 8.1
**Kernel version:** 4.4.126. 

We are building a product based on RK3399 using Android 8.1 SDK. We chose Android SDK over  linux SDK (Ubuntu) for few specific reasons that would help with our product.

For one of our features, we'd like to port our existing code based on gstreamer onto the Andriod 8.1 SDK. We'd like to leverage the HW encoding/decoding using gstreamer on Android. We've done the following,

1. Cross-compile Gstreamer using Android standalone toolchain - **done**
2. Cross-compile rockchip-linux/gstreamer-rockchip plugins using Android standalone toolchain - **done**
3. Cross-copmile rockchip-linux/mpp using Android standalone toolchain - **done**

**NOTE:** Android8.1 SDK already has a pre-built libmpp.so (vendor/rockchip/common/vpu/lib/arm64/rk3399/libmpp.so). I'm not using it as some symbols required by gstreamer-rockchip is missing in it.

When I run the below command,

`gst-launch-1.0 videotestsrc num-buffers=512 ! video/x-raw,format=NV12,width=1920,height= 1080,framerate=30/1  ! queue ! mpph264enc ! queue ! h264parse ! mpegtsmux ! filesink location=/home/linaro/2k.ts
`
I get errors from the kernel vpu_service (rk-codec), given below is the output of dmesg,

```
[14860.988234] rk_vcodec: vpu_service_ioctl:1844: error: unknow vpu service ioctl cmd 40086c01
[14861.094714] rk_vcodec: reg_init:1217: error: translate reg address failed, dumping regs
[14861.094790] rk-vcodec ff650000.vpu_service: reg[00]: 00000000
[14861.094801] rk-vcodec ff650000.vpu_service: reg[01]: 00000000
[14861.094810] rk-vcodec ff650000.vpu_service: reg[02]: 00000000

```

This looks like some mismatch between the ioctls. I do see some mismatch between the ioctls in mpp library and my current Android8.1 kernel version.

**Questions:** 
1. Is it possibe to run gstreamer HW enc/dec on Android 8.1 using this MPP library on RK3399?
2. Would upgrading my kernel vpu driver help with my issue or should I consider downgrading my mpp library ? 

I appreciate any inputs on this issue. 

Thank you and looking forward.

Regards,
San

**Comment by HermanChen** [comment]
Did you fix this issue?
