### ISSUE TITLE
problem: decoder EOS is lost 

### ISSUE THREAD

**Issue by mcerveny** [rockchip-linux/mpp#13]
In patch 3df2fb8 h264d_flush() was replaced by h264d_reset(),
it clears all flags including EOS and EOS flags are lost forever. EOS flags should be set after reset.

**Comment by hizukiayaka** [comment]
@HermanChen 
I suffer from the same problem.

**Comment by HermanChen** [comment]
emm, the H.264 decoder EOS flag is on fixing.
These is a special requirement that decoder must can decode after receiving EOS. We are trying to fix this with patch a2dd73c249a8b47709137c99f1a4f2e324851a72.

**Comment by mcerveny** [comment]
The patch a2dd73c seems to work for me. Ready to close.
