### ISSUE TITLE
没有找到rockchip_mpp.h头文件

### ISSUE THREAD

**Issue by dragon8609** [rockchip-linux/mpp#131]
看论坛的例子都有#include"rockchip/rockchip_mpp.h",为什么github上的源码没有？？？

**Comment by WainDing** [comment]
可能别人在此基础上封装的吧？我们的demo都在test目录下。

**Comment by dragon8609** [comment]
http://t.rock-chips.com/forum.php?mod=viewthread&tid=749&extra=page%3D1&page=4
找到原因了，不过应该也是rockchip封装的，只是封装一层应该开源出来。

**Comment by JeffyCN** [comment]
Toybrick has it's own packages, please do not ask related issues here, please go to Toybrick forum.
