### ISSUE TITLE
[RK3326] MPP_ENC_SET_SPLIT does not work.

### ISSUE THREAD

**Issue by OtherCrashOverride** [rockchip-linux/mpp#138]
Neither MPP_ENC_SPLIT_BY_CTU nor MPP_ENC_SPLIT_BY_BYTE produces any changes in the bitstream verified by h264 bitstream analyzer.

Is split/slice supported for RK3326?

**Comment by HermanChen** [comment]
MPP_ENC_SPLIT_BY_BYTE is not supported on RK3326.
MPP_ENC_SPLIT_BY_CTU is not implement yet on vepu2 which is used in RK3326
