### ISSUE TITLE
debuild: cannot build on native system

### ISSUE THREAD

**Issue by mcerveny** [rockchip-linux/mpp#15]
I cannot build debian package ("DEB_BUILD_OPTIONS=nocheck debuild  -i -us -uc -b -d  -aarmhf") on native platform (not cross-build). CMakeCross.txt is missing (see https://github.com/rockchip-linux/mpp/blob/for_linux/debian/rules#L27). Other sources like libdrm-rockchip, libmali, gstreamer-rockchip works okay.

This patch works of course (for_linux branch):
```
diff --git a/debian/rules b/debian/rules
index 8f68a7c..eafbec3 100755
--- a/debian/rules
+++ b/debian/rules
@@ -24,7 +24,6 @@ include /usr/share/dpkg/default.mk
 # This is example for Cmake (See http://bugs.debian.org/641051 )
 override_dh_auto_configure:
        dh_auto_configure -- \
-       -DCMAKE_TOOLCHAIN_FILE=/etc/dpkg-cross/cmake/CMakeCross.txt \
        -DCMAKE_BUILD_TYPE=Release \
        -DRKPLATFORM=ON \
        -DHAVE_DRM=ON
```

**Comment by hizukiayaka** [comment]
Those rules are designed for cross build.

**Comment by mcerveny** [comment]
Not happy with this answer.

**Comment by HermanChen** [comment]
Any advice for script organization?
