### ISSUE TITLE
rk3399 android7.1 mpi_enc_test default setting encode h264 files has visible blocks

### ISSUE THREAD

**Issue by hyayh** [rockchip-linux/mpp#158]
I pulled the latest mpp and rk3399-nougat, and I encountered several problems when i try to test the encoder performance using mpi_enc_test.
`mpi_enc_test -w 1280 -h 720 -t 7 -n 1000 -o /sdcard/720p.h264`
The output file 720p.h264 shows the correct dummy image but with visible strange blocks as the following picture shown.
![720p](https://user-images.githubusercontent.com/18044416/90951238-96371200-e48b-11ea-8944-cc6bd147d9c7.jpg)
When I try to encode a high resolution file, for example
`mpi_enc_test -w 2048 -h 1152 -t 7 -n 1000 -o /sdcard/1152p.h264`
The output file 1152p.h264 can not show the correct dummy image shown as the following picutre. 
![1152p](https://user-images.githubusercontent.com/18044416/90951240-9a632f80-e48b-11ea-9e2d-7fc0430b30c5.jpg)

**Comment by HermanChen** [comment]
For 720p image the blocky on chroma is ok.
There are some defects for this version hardware encoder with dummy image input.
This is fixed in new version hardware encoder in RK1109/RK1126.

But for 1152p the hardware encoder does not support width larger than 1920. So the stream is totally an error.

**Comment by hyayh** [comment]
Thanks for your reply. @HermanChen
