### ISSUE TITLE
hal_h264d_api: hal_h264d_init hard mode error, value=0

### ISSUE THREAD

**Issue by zillevdr** [rockchip-linux/mpp#16]
Hello,

todays git branch for_linux got an error:
[h264_rkmpp @ 0xa96025d0] Initializing RKMPP decoder.
mpi: mpp version: 0e51a98 author: Randy Li [build]: update the android build rules
hal_h264d_api: Assertion vcodec_type & ((0x00000200) | (0x00000001) | (0x00000002)) failed at hal_h264d_init:118
hal_h264d_api: hal_h264d_init hard mode error, value=0
hal_h264d_api: Assertion 0 failed at hal_h264d_init:165

I can't find why and need help. 

cat /proc/device-tree/compatible
rockchip,rk3288-miniarmrockchip,rk3288

ls /dev/*service
/dev/hevc-service  /dev/vpu-service

Regards zillevdr

**Comment by hizukiayaka** [comment]
Which distribution do you use? I may offer you a binary version.

**Comment by zillevdr** [comment]
I use Gentoo. There is a binary version difficult. Need cmake or make a special option?

**Comment by hizukiayaka** [comment]
Could you fetch the latest and rebuild once? Maybe you are using the broken code I am testing in the morning.

**Comment by HermanChen** [comment]
Looks like a platform detection error?

**Comment by hizukiayaka** [comment]
Yes, with this environment variable mpp_debug=0x10 and try again.

**Comment by HermanChen** [comment]
Please print the log of:
strings /proc/device-tree/compatible

**Comment by zillevdr** [comment]
/proc/device-tree/compatible are in my first comment. mpp_debug I will test in the evening (Europe time).
I have also tested the repository from LongChair at https://github.com/LongChair/mpp/tree/for_linux. The same result.

**Comment by zillevdr** [comment]
It was my fail. -DRKPLATFORM=ON was missed. Thank you for your help. This can be closed.
