### ISSUE TITLE
Support for kernel 5.x

### ISSUE THREAD

**Issue by gusarg81** [rockchip-linux/mpp#161]
Hi,

I would like to know is there a support for Kernel 5.7.6, which is the one that comes with Armbian (for rock64 hardware, Armbian Focal)?

I know that same distro version includes legacy kernel (4.x), But I just want to know.

Thanks.

**Comment by keveryang** [comment]
Hi, 
Rockchip don't have plan to support 5.7.6. we have 4.4 and 4.19 now, and may support next new LTS kernel to be release this year.
Thanks.

**Comment by gusarg81** [comment]
Damn Rockchip... Thanks for the info.

**Comment by gusarg81** [comment]
> Hi,
> Rockchip don't have plan to support 5.7.6. we have 4.4 and 4.19 now, and may support next new LTS kernel to be release this year.
> Thanks.

**Comment by bakwc** [comment]
Hi! Any chance to see it on 5.x kernel?
