### ISSUE TITLE
请问硬件解码jpeg的最佳方案

### ISSUE THREAD

**Issue by 0x6c0x62** [rockchip-linux/mpp#171]
在解码的demo：mpi_dec_test.c中，在956行
cmd->simple = (cmd->type != MPP_VIDEO_CodingMJPEG) ? (1) : (0);

也就是如果是JPEG解码，就使用的异步解码接口
解码一张jpeg会经过
mpi->poll(ctx, MPP_PORT_INPUT, MPP_POLL_BLOCK);
mpi->dequeue(ctx, MPP_PORT_INPUT, &task);
mpi->enqueue(ctx, MPP_PORT_INPUT, task);
mpi->poll(ctx, MPP_PORT_OUTPUT, MPP_POLL_BLOCK);
mpi->dequeue(ctx, MPP_PORT_OUTPUT, &task);
mpi->enqueue(ctx, MPP_PORT_OUTPUT, task);

看到
https://github.com/rockchip-linux/mpp/issues/82#issuecomment-514512030
说之前解码JPEG必须使用task，请问目前为止还是只能用task的异步模式吗？

**Comment by HermanChen** [comment]
目前还是，需要过一段之后才有时间修改
