### ISSUE TITLE
MPP_DEC_SET_OUTPUT_FORMAT设置jpg解码输出格式问题

### ISSUE THREAD

**Issue by liyungithub** [rockchip-linux/mpp#176]
环境：RK1808
用mpi_dec_test解码jpg图片，大部分解出来格式都是NV12的（MppFrame），但解到一张是YUV444SP，设置了MPP_DEC_SET_OUTPUT_FORMAT为MPP_FMT_YUV420SP，解码出来的MppFrame是MPP_FMT_YUV420SP，但BUF里的内容是绿色图片的，软转换可以解决，但耗时很大，最好出来就是NV12，怎么解决？

**Comment by liyungithub** [comment]
[veer.zip](https://github.com/rockchip-linux/mpp/files/5790431/veer.zip)

**Comment by liyungithub** [comment]
veer.zip就是解码出来格式为YUV444SP的图片

**Comment by liyungithub** [comment]
@HermanChen 帮我看看veer.zip这个文件的图片？我想了解什么样的情况会解码出来的是格式是YUV444SP？

**Comment by HermanChen** [comment]
估计是 1808 平台的解码器上没带转成 YUV420 格式的硬件，所以就没法转换格式了
