### ISSUE TITLE
ffmpeg decoders / encoders based on mpp?

### ISSUE THREAD

**Issue by YijinLiu** [rockchip-linux/mpp#18]
Do you have plan to add these decoders / encoders to ffmpeg?

**Comment by eddiecailinux** [comment]
community is working on it. here is repo for your reference: https://github.com/LongChair/FFmpeg/tree/rockchip

**Comment by hizukiayaka** [comment]
There is no plan for them since the bad hardware data path of ffmpeg. Also it is not a issue.

**Comment by YijinLiu** [comment]
Thanks, Eddie. The link is very helpful!

**Comment by dalmatele** [comment]
I've forked from LongChair and add encode features, but no luck, because of MPP has some errors with kernel driver.
https://github.com/dalmatele/mpp

**Comment by hizukiayaka** [comment]
Ask the ffmpeg author, not here.
