### ISSUE TITLE
mpph264enc rotation issues | rotation 设施问题

### ISSUE THREAD

**Issue by billythedummy** [rockchip-linux/mpp#183]
**device/模型:** RK3399

Output video from this GST pipeline (rotation=0)
以下GST流水线（rotation=0）输出的视频
```
gst-launch-1.0 -e v4l2src ! mpph264enc rotation=0 ! h264parse ! mp4mux ! filesink location=test.mp4
```
is the same as output video from this GST pipeline (rotation=2)
与以下流水线输（rotation=2）出的视频是一模一样的
```
gst-launch-1.0 -e v4l2src ! mpph264enc rotation=2 ! h264parse ! mp4mux ! filesink location=test.mp4
```

This pipeline (rotation=1) causes the entire rk3399 device to crash (unresponsive)
以下GST流水线（rotation=1）导致rk3399死机
```
gst-launch-1.0 -e v4l2src ! mpph264enc rotation=1 ! h264parse ! mp4mux ! filesink location=test.mp4
```

The output video from this pipeline (rotation=3) is severely distorted with the whole video comprising vertical bars
以下GST流水线（rotation=3）输出的视频画面完全以条条竖线构成 
```
gst-launch-1.0 -e v4l2src ! mpph264enc rotation=3 ! h264parse ! mp4mux ! filesink location=test.mp4
```

For rotation=1 and rotation=3, this mpp error message was observed
(rotation=1) 和 (rotation=3) 流水线跑的时候输出了以下信息
```
mpp[1413]: hal_h264e_vepu_v2: warnning: input buffer size 0x2fd000 is smaller than required size 0x384000
```

**More Setup Info:**
- Carrier board: Forlinx OK3399-C
- Camera: OV13850
- Kernel vers: Linux 4.4.189
- rockchip-mpp commit used: 3c5dc7fe4517f57dfb2619a59460a3e0ffc584fd

**Comment by JeffyCN** [comment]
i can repro this issue on rk3399 evb(with 4.4/4.19 BSP kernel), but seems like rk356x(with 4.19 kernel) work well. might due to different IP related code in MPP.

@HermanChen

**Comment by JeffyCN** [comment]
well, checking the MPP code:
mpp-release# cgrep rotation -wl
./inc/rk_venc_cmd.h
./test/mpi_enc_multi_test.c
./debian/tmp/usr/include/rockchip/rk_venc_cmd.h
./debian/librockchip-mpp-dev/usr/include/rockchip/rk_venc_cmd.h
./mpp/common/jpege_syntax.h
./mpp/hal/rkenc/h264e/hal_h264e_vepu541.c <--- it's the only h264e hal which supports rotation property
./mpp/hal/rkenc/h264e/hal_h264e_vepu541_reg.h
./mpp/hal/rkenc/h265e/hal_h265e_vepu541.c
./mpp/hal/vpu/vp8e/hal_vp8e_base.c
./mpp/hal/vpu/jpege/hal_jpege_vepu1_v2.c
./mpp/hal/vpu/jpege/hal_jpege_vepu2_v2.c
./mpp/codec/enc/jpeg/jpege_api_v2.c
./mpp/codec/enc/h264/h264e_api_v2.c
./mpp/codec/enc/vp8/vp8e_api_v2.c
./mpp/codec/enc/h265/h265e_api.c
./mpp/version.h
./mpp/vproc/inc/rga_api.h
./mpp/legacy/ppOp.cpp
./mpp/legacy/ppOp.h
./mpp/base/mpp_enc_cfg.cpp
./osal/linux/drm_mode.h

it seems like the ./mpp/codec/enc/h264/h264e_api_v2.c provide rotation property, but only rkenc support it. so only these chips(with rkvenc module) can to rotation for h264e:
mpp-release# ag HAVE_RKVENC osal/mpp_soc.cpp  -B 1
517-        ROCKCHIP_SOC_RV1108,
518:        HAVE_VDPU2 | HAVE_VEPU2 | HAVE_RKVDEC | HAVE_RKVENC,
--
529-        ROCKCHIP_SOC_RV1109,
530:        HAVE_VDPU2 | HAVE_VEPU2 | HAVE_RKVDEC | HAVE_RKVENC,
--
541-        ROCKCHIP_SOC_RV1126,
542:        HAVE_VDPU2 | HAVE_VEPU2 | HAVE_RKVDEC | HAVE_RKVENC,
--
585-        ROCKCHIP_SOC_RK3566,
586:        HAVE_VDPU2 | HAVE_VDPU2_PP | HAVE_VEPU2 | HAVE_RKVDEC | HAVE_RKVENC | HAVE_JPEG_DEC,
--
598-        ROCKCHIP_SOC_RK3568,
599:        HAVE_VDPU2 | HAVE_VDPU2_PP | HAVE_VEPU2 | HAVE_RKVDEC | HAVE_RKVENC | HAVE_JPEG_DEC,

**Comment by JeffyCN** [comment]
the newest gst mpp plugin would use rga to rotate:
https://github.com/JeffyCN/rockchip_mirrors/commit/c27f61d63aeea7104afab971902f0fc1b7680aed
