### ISSUE TITLE
能否调整解码输出格式？

### ISSUE THREAD

**Issue by JackeyLea** [rockchip-linux/mpp#187]
我的硬件是RK3399，使用官方的mpp库然后使用gstreamer的解码插件。默认解码输出为NV12格式。我修改了mpp源码中的mpp_dec_set_cfg_by_cmd函数的MPP_DEC_SET_OUTPUT_FORMAT值为YUV420P，可以正常输出，但是画面有点异常，好像在正常的结果上添加了一次绿色。
有办法完美的调整硬件解码的输出格式吗？

**Comment by HermanChen** [comment]
只有 jpeg 解码可以调整输出格式，其他格式都是固定 YUV420SP 的输出格式
