### ISSUE TITLE
mpp and rockchip "media server"

### ISSUE THREAD

**Issue by Consti10** [rockchip-linux/mpp#195]
Hello,
My rv1126 came with an application called "media server".
Unfortunately, this application has a really high end-to-end latency. (in the range of 1s while we aim for <70ms).
Therefore, I want to build a "raspivid" - style program for rv1126.

I am wondering, 
a) is the source code of "media server" available and
b) is "media server" built on top of mpp or something else ?

**Comment by HermanChen** [comment]
media server is on top of mpp
You can use mpp to build base codec layer.

**Comment by Consti10** [comment]
thanks.
Is it open or closed source (media server) ?

**Comment by HermanChen** [comment]
The media server layer is rkmedia. It is also open source.

**Comment by Consti10** [comment]
Thanks. For those coming across the issue, here is the code:
https://github.com/rockchip-linux/rkmedia
