### ISSUE TITLE
请教下解码性能问题？

### ISSUE THREAD

**Issue by liyungithub** [rockchip-linux/mpp#205]
输入echo 0x100 > /sys/module/rk_vcodec/parameters/debug后，dmesg有解码相关耗时的打印，如下图：
![image](https://user-images.githubusercontent.com/22513244/119751854-82af5080-bece-11eb-990b-09b09a42951f.png)
这个是每帧图像解码的耗时吗？这个是我在rk1808平台解码1080p视频的打印，是不是意味着rk1808解码1080p视频平均每帧耗时8ms，1秒能解125帧，但官方的资料显示，rk1808解码1080p图像性能是每秒60帧，两者不一致，那到底怎么理解这8ms？谢谢！

**Comment by liyungithub** [comment]
@HermanChen 可以解答下？谢谢了！

**Comment by HermanChen** [comment]
是的，理解正确
但这个只是硬件开销，实际上软件还有部分开销，到不了 125fps

**Comment by liyungithub** [comment]
好的，谢谢了！
