### ISSUE TITLE
编码报错：check_is_mpp_packet pointer failed on check mpp: mpp_packet: mpp_packet_copy invalid input

### ISSUE THREAD

**Issue by liuguohuan-xiezuo** [rockchip-linux/mpp#220]
把mpi_enc_test.c的代码移植出来写一个接口，开始编码就报错
mpp[11553]: mpp_packet: check_is_mpp_packet pointer 0x7faa4e2700 failed on check
mpp[11553]: mpp_packet: mpp_packet_copy invalid input: dst 0x7faa4e2700 src 0x55805f7c88
这个报错应该跟ret = mpi->control(ctx, MPP_ENC_GET_HDR_SYNC, &packet);这个接口有关，之前我用的MPP_ENC_GET_EXTRA_INFO，发现已经启用了，提示我用MPP_ENC_GET_HDR_SYNC，但用了这个接口就一直上面的报错，是我的packet有什么错误吗，代码基本跟源码是一样的

**Comment by HermanChen** [comment]
MPP_ENC_GET_HDR_SYNC 这个的接口参数和使用方法需要仔细看下，和之前的参数不同
