### ISSUE TITLE
OpenMax IL

### ISSUE THREAD

**Issue by shantur** [rockchip-linux/mpp#227]
Hi,

As i read that MPP supports OpenMAX, is there any OpenMax implementation for linux available for mpp?

Thanks

**Comment by HermanChen** [comment]
The openMax implement is for Android. The linux version is not implemented.

**Comment by shantur** [comment]
Thanks for confirming. Any plans to implement for linux or any pointers if its possible to use Android implementation and convert to linux?

**Comment by HermanChen** [comment]
No plan yet.
It is possible but will be huge changes.
