### ISSUE TITLE
gstreamer解码框架能否调用MPP硬件解码

### ISSUE THREAD

**Issue by XingP** [rockchip-linux/mpp#233]
在SDK编译出来的Debian系统下安装了libgstreamer的依赖，然后调用其API进行视频的解码。
此时串口会有MPP的打印出现，请问是MPP对gstreamer有支持吗？不过好像实际上并没有应用到硬件解码，又是什么情况呢？

解码方式为VP8时，
mpp[6262]: mpp_info: mpp version: 41c9c809 author: sayon.chen    2020-12-24 [mpp2str]: Add rc_gop_mode 2 str
mpp[6262]: mpp_rt: NOT found ion allocator
mpp[6262]: mpp_rt: found drm allocator
mpp[6262]: mpp: deprecated block control, use timeout control instead
mpp[6262]: mpp_info: mpp version: 41c9c809 author: sayon.chen    2020-12-24 [mpp2str]: Add rc_gop_mode 2 str
mpp[6262]: mpp: deprecated block control, use timeout control instead
mpp[6262]: mpp_info: mpp version: 41c9c809 author: sayon.chen    2020-12-24 [mpp2str]: Add rc_gop_mode 2 str
mpp[6262]: mpp: deprecated block control, use timeout control instead
……
看CPU占用，此时在进行软解。

解码方式为H264时，
mpp[6492]: mpp_info: mpp version: 41c9c809 author: sayon.chen    2020-12-24 [mpp2str]: Add rc_gop_mode 2 str
mpp[6492]: mpp_rt: NOT found ion allocator
mpp[6492]: mpp_rt: found drm allocator
mpp[6492]: mpp: deprecated block control, use timeout control instead
mpp[6492]: h264d_api: is_avcC=1
mpp[6492]: h264d_sps: ERROR: Not support chroma_format_idc=3.
mpp[6492]: mpp: deprecated block control, use timeout control instead
mpp[6492]: mpp: deprecated block control, use timeout control instead
mpp[6492]: mpp_info: mpp version: 41c9c809 author: sayon.chen    2020-12-24 [mpp2str]: Add rc_gop_mode 2 str
mpp[6492]: mpp: deprecated block control, use timeout control instead
mpp[6492]: h264d_api: is_avcC=1
mpp[6492]: h264d_sps: ERROR: Not support chroma_format_idc=3.
mpp[6492]: mpp: deprecated block control, use timeout control instead
mpp[6492]: mpp: deprecated block control, use timeout control instead
……
mpp[6492]: mpp: deprecated block control, use timeout control instead
mpp[6492]: mpp_buffer: mpp_buffer_put invalid input: buffer NULL from vdpu34x_h264d_deinit
mpp[6492]: hal_bufs: hal_bufs_deinit invalid NULL input
mpp[6816]: mpp: deprecated block control, use timeout control instead
……
这种情况下解码过程停止，画面不更新。

**Comment by XingP** [comment]
看《MPP开发参考》里的系统架构，MPP是可以通过MPI对接gstreamer的，这里是配置的问题吗，有没有什么MPI 对接中间件软件的说明可以参考？谢谢

**Comment by JeffyCN** [comment]
The debian SDK supports gstreamer + mpp by default.
If any thing wrong, please contact FAE for support, for example update to the newest release SDK.
