### ISSUE TITLE
mpp buffer group

### ISSUE THREAD

**Issue by Allenhe123** [rockchip-linux/mpp#235]
众所周知：因为nocache的原因从mpp解码后的drm/rga buffer中copy数据非常慢，而我的业务场景恰恰是需要将解码后的数据拷贝到我们自己创建的ion buffer中，所以可不可以用我们自己创建的ion buffer替换mpp自动生成的buffer group中的buffer？ 可以提供一下示例代码吗？ 谢谢。
@HermanChen

**Comment by JeffyCN** [comment]
we would prefer to use RGA hw module for image copying.
and it's also possible to import any external dma buf(fd) to the group:
  MppBufferInfo info = { 0, };
  MppBuffer mbuf = NULL;
  info.type = MPP_BUFFER_TYPE_DRM;
  info.size = size;
  info.fd = fd;
  mpp_buffer_import (self->ext_group, &info, &mbuf);

**Comment by lawaarch** [comment]
说的啥啊  没看懂
