### ISSUE TITLE
DRM allocator appears to use 8X more memory than it should

### ISSUE THREAD

**Issue by OtherCrashOverride** [rockchip-linux/mpp#24]
The following line appears to incorrectly calculate the size:
https://github.com/rockchip-linux/mpp/blob/release/osal/allocator/allocator_drm.c#L189

```dmcb.size = dmcb.width * dmcb.bpp;```
should probably be:
```dmcb.size = dmcb.width * (dmcb.bpp / 8);```

bpp=bits per pixel. there are 8bits in a byte. size is in bytes.

**Comment by hizukiayaka** [comment]
Thanks, it actually doesn't matter, since that field is filled by kernel, that line doesn't have any effect.

**Comment by OtherCrashOverride** [comment]
Coincidentally, while debugging a project, I came to the same conclusion.  The line should be removed to since the field is an output and not an input to the IOCTL.

**Comment by hizukiayaka** [comment]
So this line is just an useless sentence, I will remove it in the next release version.
