### ISSUE TITLE
Question: Does the hardware "driver" for the encoder come with mpp or kernel ?

### ISSUE THREAD

**Issue by Consti10** [rockchip-linux/mpp#243]
Hello,

Am I right to assume that the encoder driver (e.g. the code that talks to the encoder hardware, e.g. changes registers related to encoding settings) does not come with the kernel, but rather mpp ?

Since the code looking closest to the encoder "driver" on rv1126 I can find is here:
https://github.com/rockchip-linux/mpp/blob/develop/mpp/hal/rkenc/h264e/hal_h264e_vepu541.c

But on the other hand, the kernel code also has the following encoding related directories:
kernel/drivers/video/rockchip/mpp and
kernel/drivers/media/platform/rockchip-vpu (this directory is unused code on rv1126 I think).

**Comment by HermanChen** [comment]
> 
> 
> Hello,
> 
> Am I right to assume that the encoder driver (e.g. the code that talks to the encoder hardware, e.g. changes registers related to encoding settings) does not come with the kernel, but rather mpp ?
> 
> Since the code looking closest to the encoder "driver" on rv1126 I can find is here:
> https://github.com/rockchip-linux/mpp/blob/develop/mpp/hal/rkenc/h264e/hal_h264e_vepu541.c
> 
> But on the other hand, the kernel code also has the following encoding related directories:
> kernel/drivers/video/rockchip/mpp and
> kernel/drivers/media/platform/rockchip-vpu (this directory is unused code on rv1126 I think).

Yes, userspace mpp generate the whole set of register values and send to kernel driver rockchip/mpp as a task. Then the kernel driver serializes all the tasks from userspace and set to hardware.

**Comment by Consti10** [comment]
Thanks
