### ISSUE TITLE
mpp 解码后的YUV格式可以指定成YUV420P吗？

### ISSUE THREAD

**Issue by whwalker** [rockchip-linux/mpp#268]
arm64的环境， mpp解码后，"fmt  = mpp_frame_get_fmt(decoder->frame)"  ，打印fmt显示是MPP_FMT_YUV420SP，可以指定成直接输出MPP_FMT_YUV420P 吗？

**Comment by JeffyCN** [comment]
不支持，需要另外转换，比如用rga接口或者gpu(opengles)
