### ISSUE TITLE
Towards an example for rendering MPP output with DRI2

### ISSUE THREAD

**Issue by ydirson** [rockchip-linux/mpp#27]
As I am having performance issues with my experimental usage of MPP in our in-house app, I have started to replicate what I did in the form of an example, by extending the official decoder test, in https://github.com/BladeGroup/mpp - in the hope that a complete example may also help others to gain time (when it is correct, obviously ;).

This example is slightly different from our app (where SDL already initializes a lot of graphics stuff), and I went into DRI2 initialization manually, but I'm apparently missing something, as drmPrimeFDToHandle() is still failing with EPERM on all frames. Use "-m 2" to activate display using DRI2.

**Comment by hizukiayaka** [comment]
Ask the SDL, not us.
