### ISSUE TITLE
RGA convert nv12 to rgb crash

### ISSUE THREAD

**Issue by Allenhe123** [rockchip-linux/mpp#277]
source: 1920x1080 nv12
dst: 960 x 540 rgb
rga will crash!

If dst use: 960 x 480 rgb, it is ok.

Is this a limit of rga which only support special resolution?

**Comment by HermanChen** [comment]
I think it is config error in mpp.

**Comment by Allenhe123** [comment]
it was caused by the width and height must be 16 align.
