### ISSUE TITLE
Any example code demonstrating multi-stream decoding/encoding without display?

### ISSUE THREAD

**Issue by changtimwu** [rockchip-linux/mpp#281]
Here is one of the RK3588 feature highlights 
<img width="721" alt="CleanShot 2022-03-18 at 05 14 01@2x" src="https://user-images.githubusercontent.com/400410/158896350-819baf5e-bb89-4ff2-9067-72514baaf989.png">

While 32-stream decoding and 16-stream encoding might look powerful, I couldn't find any code clip demonstrating more than 2 stream decoding.

I'd like to know if it's doable in RK 35xx series.  Thanks a lot.

**Comment by changtimwu** [comment]
Sorry, maybe I should try standard gst command first.  Still waiting for my RK board arrival. Thanks,though.

**Comment by HermanChen** [comment]
Use mpi_dec_multi_test or mpi_dec_test with -s option you can decode multi stream at one time.
