### ISSUE TITLE
rga_copy error 

### ISSUE THREAD

**Issue by baoson202** [rockchip-linux/mpp#287]
i call rga_copy on my rk3399 board and result : 
      ret = rga_copy(ctx,src_frm,dst_frm);
application log error :

mpp[8287]: mpp_rt: NOT found ion allocator
mpp[8287]: mpp_rt: found drm allocator
mpp[8287]: mpp_log: rga ioctl failed errno:14 Bad address

Please help me how to fix it ! thanks

**Comment by HermanChen** [comment]
Do not use the rga test in mpp.
Try https://github.com/AngerLee/librga
