### ISSUE TITLE
使用camera_source代码，mpi_enc_test -w 640 -h 480 -t 7 -f 8 -i /dev/video0 -o /userdata/1131.h264，画面有横细线

### ISSUE THREAD

**Issue by Csf-mycount** [rockchip-linux/mpp#289]
![image](https://user-images.githubusercontent.com/56286003/162145932-551dc91b-f8c9-4d09-b118-3dec7e2c9f35.png)
请问怎么解决呢，测试过无横细线单独yuv编码成h264播放没问题，说明编码是没问题的，问题应该出在v4l2?

**Comment by HermanChen** [comment]
是否有 cpu 拷贝？看起来是 cpu 拷贝的 cache 问题

**Comment by Csf-mycount** [comment]
没有拷贝，单纯的从摄像头中获取图像编码成h264文件播放会如上图，然后测试了一下只拿yuv格式图像一帧一帧看又没问题，然后又测试用yuv格式视频通过mpi_enc_test编码成h264也没问题

**Comment by HermanChen** [comment]
估计还是有 cpu 拷贝的过程，或者其他器件在做拷贝，这种的拉丝比较像是 cache 问题，或者是 buffer 管理有问题，同一个 buffer 被同时读写了

**Comment by Csf-mycount** [comment]
我是直接应用mpi_enc_test.c来测试，请问你们有同样测试过吗?

**Comment by Csf-mycount** [comment]
还有，假如我在这个位置延时了一下就不会有横线，但是播放的视频会有快进的感觉
![image](https://user-images.githubusercontent.com/56286003/164200022-c5392e00-0ca8-44c7-9de9-e03674a5675f.png)

**Comment by Csf-mycount** [comment]
ok 解决了
![image](https://user-images.githubusercontent.com/56286003/164209235-841b3403-945c-44fd-8d50-c1cf7de3d8af.png)

**Comment by Csf-mycount** [comment]
已解决，用usb摄像头时候不使用mpp_frame_set_buffer(frame, cam_buf)，重新memcpy(buf, p->cam_ctx->fbuf[cam_frm_idx].start, p->width * p->height *2)， 再使用mpp_frame_set_buffer(frame, p->frm_buf)就不会有横线
