### ISSUE TITLE
关于mpp多路解码问题

### ISSUE THREAD

**Issue by boboding** [rockchip-linux/mpp#293]
以RV1126 支持4K H.264/H.265 视频编码和解码为例

mpp支持4路的 H264格式RTSP流1920*1080分辨率， hor_stride与ver_stride分别为1920和1088 。

如果mpp解码为H265格式hor_stride与ver_stride为2304和1080，4路情况下解码后总的超过了4K，这样也支持4路吗？
还是说无论mpp解码成什么样格式，只要输入在1920*1080分辨率以下就可以支持4路解码？

**Comment by HermanChen** [comment]
stride 是内存排布，主要看实际编码的有效尺寸大小
比如 1080p 的有效数据，就算 stride 扩大到 4096，也是一样的 1080p 大小的编码负载

**Comment by boboding** [comment]
谢谢
