### ISSUE TITLE
mpp_dev_ioctl:545: unknow mpp ioctl cmd 40086c03

### ISSUE THREAD

**Issue by dalmatele** [rockchip-linux/mpp#30]
When I test mpi_enc_test -i small.yuv -w 560 -h 320 -f 4 -t 7 -d 3 -o output.mp4 
I've got that error in output log:
mpp_dev_ioctl:545: unknow mpp ioctl cmd 40086c03
mpp_dev_ioctl:545: unknow mpp ioctl cmd 40086c04
I run mpp with RK3328 on rock64 board.
I've used  the newest code mpp version.

**Comment by hizukiayaka** [comment]
Update the kernel driver and use the match kernel header to build the library.

**Comment by FallingSnow** [comment]
I'm getting `rk_vcodec: vpu_service_ioctl:1844: error: unknow vpu service ioctl cmd 40086c01`.

Using latest kernel git build
```
$ uname -a
Linux divinity 4.4.114-1 #2 SMP Sun Mar 4 17:14:55 PST 2018 aarch64 GNU/Linux
```
