### ISSUE TITLE
https://github.com/rockchip-linux/linux-rga 被删除了

### ISSUE THREAD

**Issue by liyuming1978** [rockchip-linux/mpp#304]
那怎么去获取rga的  so呢， 至少so要能获取

**Comment by liyan110120999** [comment]
同问

**Comment by nyanmisaka** [comment]
https://github.com/airockchip/librga

应该是搬到airockchip的仓库了。
rockchip-linux经常有删仓库的习惯，之前还删过ffmpeg。所以有用的最好随手fork一下。

**Comment by liyuming1978** [comment]
好
