### ISSUE TITLE
硬解码关联surface与不关联surface的性能差异

### ISSUE THREAD

**Issue by chfdeng** [rockchip-linux/mpp#307]
请假下，我用android实际测试rk3568时，在硬解码关联surface时勉强可以9路，不关联suface时只能勉强6路，这是为什么呢，是因为关联surface时硬解码后直接调用gpu渲染，而不关联surface时需要复制到内存中导致额外的消耗吗？望赐教！！

**Comment by HermanChen** [comment]
有显示的话会消耗 DDR 带宽，影响解码器性能

**Comment by chfdeng** [comment]
可是我实际测试结果是有显示时能流畅解码的路数比没显示时的路数还多，这是为什么呢@[HermanChen](https://github.com/HermanChen)

**Comment by HermanChen** [comment]
是不是有关联surface的时候走的零拷贝路径，没关联surface时有cpu数据拷贝？top 看下负载

**Comment by chfdeng** [comment]
这是不关联surface的：
![no surface](https://user-images.githubusercontent.com/13350298/177066779-52a671be-89c8-46a8-9cd3-1785bf909aaa.png)
这是关联surface的：
![surface](https://user-images.githubusercontent.com/13350298/177066817-96dbe376-af44-4929-8764-bca9745e7c92.jpg)
可以看出在不关联surface的情况下cpu和内存占用都比较大

**Comment by HermanChen** [comment]
总的cpu用量区别不大
echo 0x100 > /sys/module/rk_vcodec/parameters/mpp_dev_debug
看看硬件运行时间，这个路径是手打的，不一定对，需要在板上验证下目录名

**Comment by chfdeng** [comment]
这是不关联surface的：
![没显示](https://user-images.githubusercontent.com/13350298/177069026-4517045e-f3f8-44aa-ae8f-992312677cde.jpg)
这是关联surface的：
![显示](https://user-images.githubusercontent.com/13350298/177069047-beaed39f-024f-41d5-90a9-49a34715b805.jpg)

**Comment by chfdeng** [comment]
是不是不关联的话需要多一次数据copy导致的额外消耗呢@[HermanChen](https://github.com/HermanChen)

**Comment by HermanChen** [comment]
嗯，应该是，看硬件时间是差不多的

**Comment by chfdeng** [comment]
好的，非常感谢

**Comment by xuhaijia** [comment]
@chfdeng 你好，请问您是如何在android上实现关联surface的，最近想开发这个功能，能否借鉴下您的demo
