### ISSUE TITLE
rgaconvert can`t find proper device, /dev/video10, /dev/rga

### ISSUE THREAD

**Issue by nikitos1550** [rockchip-linux/mpp#31]
Hello!

I am trying to use gstreamer EXTRA rockchip plugins **rgaconvert** . According to sources it requires /dev/video10 device, but in mine rk3328 there is no such device. Also I checked mpp sources and seems 
mpp lib using /dev/rga, and I also don`t have such device. 

What is proper way to use rgaconvert?

**Comment by nikitos1550** [comment]
Seolved https://github.com/rockchip-linux/kernel/issues/28

**Comment by unoonu** [comment]
Hello @nikitos1550

I try but fail. i used rgaconvert ,but  show error about "Cannot identify device. ''
i miss something step?
how to solve it?
