### ISSUE TITLE
如何开启test例程的运行log

### ISSUE THREAD

**Issue by lozenyin** [rockchip-linux/mpp#312]
我在运行例程mpi_dec_test的时候没有打印运行信息，这个和先前测试的不一样。请问一下要如何开启运行信息打印？

`
root@kylin:/home/kylin/mpp/build/linux/aarch64/test# sudo ./mpi_dec_test -t 7 -i /home/kylin/test11.h264 -n 10
root@kylin:/home/kylin/mpp/build/linux/aarch64/test#
`

**Comment by xueshenan** [comment]
使用journalctl -f 命令可以查看到mpp_log输出的内容。

**Comment by HermanChen** [comment]
或者 export mpp_syslog_perror=1
