### ISSUE TITLE
Encoder example?

### ISSUE THREAD

**Issue by teaglin** [rockchip-linux/mpp#319]
Hi,

Unfortunately ffmpeg/opencv do not support rock chip as a hw encoder. I see there are some encoder examples, do those operate directly on RGB data for encoding? Do you have any examples of encoding opencv mat directly to h264/hevc?

**Comment by HermanChen** [comment]
Try the mpi_enc_test in mpp. It supports RGB encoding. The opencv mat is using cpu malloc memory. It can not be directly import to hw encoder.

**Comment by teaglin** [comment]
Thanks, I will take a look. Also do you know why hw decoding was implemented in ffmpeg, but not encoding? Any idea on if/when that might happen?

**Comment by HermanChen** [comment]
The ffmpeg mpp encoder plugin is not developed yet.
