### ISSUE TITLE
all tests run, but don't print anything

### ISSUE THREAD

**Issue by Timvrakas** [rockchip-linux/mpp#328]
./mpp_platform_test for example, just runs and returns with no information printed.

I built from latest source, on a ROCK 3A, RK3568, with [rock-3a-ubuntu-focal-server-arm64-20221001-0212-gpt.img.xz](https://github.com/radxa-build/rock-3a/releases/download/20221001-0110/rock-3a-ubuntu-focal-server-arm64-20221001-0212-gpt.img.xz)

I can see `/dev/mpp_service`

What am I doing wrong?

**Comment by HermanChen** [comment]
export mpp_syslog_perror=1 then run

**Comment by Timvrakas** [comment]
Ah, I didn't realize the log output would end up in /var/log/syslog, rather than printed directly.

That export does not appear to change anything, but I now have the encoder working.

Is there a way to have the test programs print to stdout, rather than to syslog?

**Comment by Timvrakas** [comment]
I find this behavior strange:

> mpi_enc_test: failed to open input file big_buck_bunny_1080p_H264_AAC_25fps_7200K-nv12.yuv
mpi_enc_test: create default yuv image for test

If the file specified does not exist, I would expect the program to exit with error.

**Comment by HermanChen** [comment]
Good point. We will change it.

**Comment by HermanChen** [comment]
Change the os_log_xxx function to printf in os_log.cpp at osal/linux
