### ISSUE TITLE
I use mpp to decode the video file hard and find that the decoding delay is relatively large. Please see the attachment for the video and log.

### ISSUE THREAD

**Issue by Yg-Luo** [rockchip-linux/mpp#334]
I use mpp to decode the video file hard and find that the decoding delay is relatively large. Please see the attachment for the video and log. Most videos are normal with little delay.
[MPP硬解延时100ms.zip](https://github.com/rockchip-linux/mpp/files/9875487/MPP.100ms.zip)

**Comment by HermanChen** [comment]
加上 IMEDIATE_OUT 的 control

**Comment by HermanChen** [comment]
这个也要看片源，有一片源的显示序和解码序差别就是很大的

**Comment by Yg-Luo** [comment]
> 加上 IMEDIATE_OUT 的 control

请教一下这个命令的control对应的第三个参数是什么

**Comment by HermanChen** [comment]
整个 U32 变量为 1，把这个变量地址送进去

**Comment by Yg-Luo** [comment]
> 整个 U32 变量为 1，把这个变量地址送进去

嗯，这样验证过了，输出延时还是一样的

**Comment by HermanChen** [comment]
片源里有没有 B 帧？还是只有 I 帧和 P 帧？

**Comment by Yg-Luo** [comment]
> 片源里有没有 B 帧？还是只有 I 帧和 P 帧？
是有B帧的
![有B帧](https://user-images.githubusercontent.com/71999965/198537778-ec424989-b8b3-4b59-ac3e-cb6ddefb41bc.png)

**Comment by HermanChen** [comment]
有 B 帧就很难保证时延了，解码序和显示端不一致，时延就会不断波动
