### ISSUE TITLE
mpi_dec_test -f 4不生效

### ISSUE THREAD

**Issue by chuqingq** [rockchip-linux/mpp#345]
用mpi_dec_test 解码h264，通过-f 4设置format参数为yuv420p，但是解码出来仍然是yuv420sp。

**Comment by HermanChen** [comment]
H.264 解码不支持输出格式转换，解码输出格式转换只有 jpeg 有支持

**Comment by chuqingq** [comment]
谢谢！
我现在的场景是想先解码然后编码，问题是如果对pix-fmt为yuv420p编码没问题（有色彩），如果对pix-fmt为yuv420sp编码后是没有色彩的。如果解码只能是yuv420sp，那编码是不是需要指定输入的pix-fmt是yuv420sp？如何指定？
