### ISSUE TITLE
Segmentation Fault on mpi_dec_test with Rock Pi 4c+

### ISSUE THREAD

**Issue by cpmbailey** [rockchip-linux/mpp#352]
./mpi_dec_test -i demo.h264
Segmentation fault

uname -a
Linux rock-4c-plus 4.4.194-10-rk3399-rockchip-gf9d08dbd6762 #1 SMP Mon Oct 24 18:23:12 CST 2022 aarch64 GNU/Linux

**Comment by HermanChen** [comment]
Please provide the error log
