### ISSUE TITLE
decode_get_frame后frame为0

### ISSUE THREAD

**Issue by Uhao-P** [rockchip-linux/mpp#354]
在使用[rtsp+ffmpeg+mpp](https://github.com/MUZLATAN/ffmpeg_rtsp_mpp)项目测试时，其中`ret = mpi->decode_get_frame(ctx, &frame);`中返回的ret为0，但是frame也是0。读取的rtsp流格式如下：
![image](https://user-images.githubusercontent.com/42427430/216635674-57506c3e-4faa-4178-8ebf-47a09818760f.png)

直接使用`mpi_dec_test`可以直接对h264文件解码

**Comment by HermanChen** [comment]
可以直接用 mpi_dec_test 解码

**Comment by MapleAura** [comment]
同样的问题 请问解决了吗

**Comment by Felix-fz** [comment]
您好请问最终解决这个问题了吗？
