### ISSUE TITLE
rk35568编码 分片单独编码

### ISSUE THREAD

**Issue by lawaarch** [rockchip-linux/mpp#362]
我在使用 rk3568硬件进行编码时，发现编码器将其分片熵编码。我参考MPP开发手册，了解到此，我想请教各路大佬，为何会出现这样现象，怎么设置不让熵编码。希望开发者早日更新开发手册。好多都是我自己测出来的。

**Comment by HermanChen** [comment]
3568 手册上写的是 1080p 的规格，264 编码在 1080p 以下是正常的，在 1080p 以上能支持，但是不建议使用，这个是我们IP开发验证功能用的……

**Comment by lawaarch** [comment]
> 3568 手册上写的是 1080p 的规格，264 编码在 1080p 以下是正常的，在 1080p 以上能支持，但是不建议使用，这个是我们IP开发验证功能用的……

非常感谢开发者的及时回复，我肯定是拿了一个假的开发手册。有问题再叨扰

**Comment by HermanChen** [comment]
并不是……
我们的文档水平太水了。。。。
