### ISSUE TITLE
mpp 解码后，获取frame的宽度高度等信息 为0

### ISSUE THREAD

**Issue by callanzhao** [rockchip-linux/mpp#372]
使用ffmpeg，设置MPP_DEC_SET_PARSER_SPLIT_MODE 为0，然后读取mp4视频，获取AVPacket，再转成MppPacket,  put_packet后，解码函数decode_get_frame 返回的0， frame不等于0，然后通过mpp_frame_get_width，mpp_frame_get_height 获取frame的宽度和高度，数值都是0，这是解码没解对，还是获取的就是0呢。

同样的过程，如果不使用ffmpeg，MPP_DEC_SET_PARSER_SPLIT_MODE 设置为1，然后读取264裸码流，put_packet后，获取解码的frame，这个用mpp_frame_get_width获取的frame值就有数值是对的。这是为啥呢

**Comment by HermanChen** [comment]
PARSER_SPLIT_MODE 是 mpp 内部分帧模式，如果不开这个模式，外部送入的数据就必须是以一帧为单位送入，外部需要有个分帧的功能。

**Comment by callanzhao** [comment]
ffmpeg 处理后的AVPACKET是一帧的数据 送入的
