### ISSUE TITLE
3588 关于mpp的编码

### ISSUE THREAD

**Issue by sniperMt** [rockchip-linux/mpp#376]
你好，我使用extra_info会又sps sei信息，用文档的 HDR那个就没有了，还有就是 我参考的是RK3399的代码，发现 送空的时候没问题，送1080p yuv420P的数又问题，就是 SDK里面的MPP的文档啥时候更新

**Comment by HermanChen** [comment]
不太理解说的是什么问题。。。。
一个问题一个问题分开来讲
