### ISSUE TITLE
rk3588解码线程阻塞

### ISSUE THREAD

**Issue by NCU-xiaoxiaobai** [rockchip-linux/mpp#381]
我调用了4路解码, 此时解码线程正常运行, CPU接近满载, 一切都是正常的. 但是当我再开一路解码时, 会出现某个或多个解码线程阻塞, 解码器内部线程mpp_dec_hal_thread阻塞在mpp_dec_normal.cpp 787行, mpp_dec_parser_thread线程阻塞在mpp_dec_normal.cpp 701行
![image](https://user-images.githubusercontent.com/51814939/229449148-9c6c1575-15a2-4493-84c1-e6458886f4f0.png)
![image](https://user-images.githubusercontent.com/51814939/229449567-e3ce5221-afd0-43dd-bf24-4747217eaa1f.png)

我想请教一下这种情况会是什么原因导致解码线程阻塞

**Comment by NCU-xiaoxiaobai** [comment]
我想去验证parser线程阻塞是不是第一种情况即no task slot for output. 在5个解码线程全部阻塞前的日志如下,通过日志我无法判断是否是slot的问题
![image](https://user-images.githubusercontent.com/51814939/229453922-a2b33b9f-2768-4545-9437-c537b9f7d073.png)

**Comment by HermanChen** [comment]
这应该是输出没有取走的问题

**Comment by NCU-xiaoxiaobai** [comment]
每次我都是放入完整的一帧数据, 当调用get_frame第一次获取到mpp_frame后就立刻返回了.
按照你的思路, 我放入一帧数据, 解码后可能会有多帧数据, 而我只取了一帧数据(或者说输出有一帧,而我只取出了一部分),那我想请教一下有什么办法判断放入一帧压缩数据后, 输出是否已全部取出的方法

**Comment by HermanChen** [comment]
可以一直取，直到取失败为止

**Comment by NCU-xiaoxiaobai** [comment]
请问一下解码输出的格式一定是NV12格式吗,还是可以通过解码参数去配置

**Comment by HermanChen** [comment]
走 rkvdec 的视频解码都是 nv12 输出，只有 jpeg 解码可以修改一些的输出格式
