### ISSUE TITLE
rk3588 安装mpp库并运行mpi_dec_test 的问题

### ISSUE THREAD

**Issue by danke1896** [rockchip-linux/mpp#384]
当我们使用apt安装的mpp_test 中的mpi_dec_test 进行解码时,可以正常解码.
但使用github//rockchip-linux /mpp-release编译后的test中的mpi_dec_test解码时,汇报如下错误:
![Screenshot from 2023-04-12 03-16-56](https://user-images.githubusercontent.com/29629199/231341491-8d00d4e1-ebf2-4c3f-ae55-0460e7675595.png)
运行的系统为开发板自带的debian系统,内核为5.10.66,
运行mpp_platform_test, 输出如下:
![Screenshot from 2023-04-12 03-18-49](https://user-images.githubusercontent.com/29629199/231341699-f7f74f8f-e3e1-491a-8068-319afeee3e60.png)
运行mpi_runtime_test,结果如下:
![Screenshot from 2023-04-12 03-26-32](https://user-images.githubusercontent.com/29629199/231341783-85350be7-7888-41cd-b54a-5a3f661fa5c7.png)

**Comment by HermanChen** [comment]
release 分支很旧了，不要继续使用

**Comment by danke1896** [comment]
使用mpp-develop源码编译完,运行mpi_dec_test解码时会报段错误,syslog 中输出的日志:
![Screenshot from 2023-04-12 04-11-06](https://user-images.githubusercontent.com/29629199/231368738-78a0d39c-a136-4224-8585-d4d9b4df8346.png)

**Comment by HermanChen** [comment]
这个看起来是使用了 dma-heap 来解码，但权限有问题，导致 dmaheap 打不开

**Comment by danke1896** [comment]
已解决,是权限的问题,加完权限就可以了.
