### ISSUE TITLE
H264 decode first frame can't get

### ISSUE THREAD

**Issue by cgllv** [rockchip-linux/mpp#386]
I have a h264 file, the first frame is I frame, when I run get_frame and dump file, it will return when mpp_frame_get_info_change, I think I frame should decode directly, I should get a picture, but I can't, is it right? how to get first I frame directly? this problem really doubt my  a lot.

**Comment by HermanChen** [comment]
info change 帧是把码流的宽高反馈出来，让外部来提供 buffer 用的，参考下 mpi_dec_test
如果要第一帧直接出数据的话，需要预先分配和 commit buffer 到 buffer group 并 SET_EXT_BUFFER_GROUP，然后用 SET_FRAME_INFO 配置好码流宽高，这样才能让第一帧出来就直接是数据，可以看下 vpu_api 里怎么处理的。
