### ISSUE TITLE
mpp_buffer_get问题

### ISSUE THREAD

**Issue by NCU-xiaoxiaobai** [rockchip-linux/mpp#391]
测试代码如下: 
    ret = mpp_buffer_get(NULL, &mpp_buffer, buf_size);
    if (ret) {
        mpp_err("failed to get buffer for input frame ret %d\n", ret);
        goto done;
    }

    MppFrame frame = NULL;
     mpp_frame_init(frame);
     
    mpp_frame_set_buffer(frame, mpp_buffer);
    MppBuffer buf = mpp_frame_get_buffer(frame);

   打印地址发现mpp_buffer不为空, 但是buf为空,这是什么原因?

**Comment by HermanChen** [comment]
mpp_frame_init(&frame);
