### ISSUE TITLE
H264 编码支持垂直镜像吗？

### ISSUE THREAD

**Issue by lh0104** [rockchip-linux/mpp#392]
根据 hal_h264e_vepu541_reg.h 定义的结构体 reg022 中的 src_mirr 只占1位，只能传值 0 或 1。如下图
![image](https://user-images.githubusercontent.com/52019108/234506777-136d354b-5aa0-4d73-bda0-14a4f3ddffae.png)

而根据 Rockchip_Developer_Guide_MPP_CN.pdf，编码器是支持垂直镜像的，可以传值 2。
![image](https://user-images.githubusercontent.com/52019108/234507557-ca173bf7-e808-4475-ac25-a7ec9874d788.png)

**Comment by HermanChen** [comment]
一些硬件只有水平镜像的支持，上层接口的功能不一定在所有的硬件上都支持

**Comment by lh0104** [comment]
> 一些硬件只有水平镜像的支持，上层接口的功能不一定在所有的硬件上都支持

好的。JPEG 编码为什么不支持旋转 180 度？

**Comment by HermanChen** [comment]
因为这版的硬件设计上就不支持啊……
