### ISSUE TITLE
单例仅包含解码器初始化，这是普通用户和root用户执行的日志差别。不知道什么问题

### ISSUE THREAD

**Issue by Kevin4ch** [rockchip-linux/mpp#394]
![image](https://user-images.githubusercontent.com/8243696/234852880-313e8fff-e949-4e65-8424-ea0ed8cbed5e.png)
单例仅包含解码器初始化，这是普通用户和root用户执行的日志差别。不知道什么问题

**Comment by nyanmisaka** [comment]
root用户相比普通用户有权限访问ion设备，导致了mpp初始化失败。可以在内核中禁用ion。

比如 https://github.com/armbian/build/pull/5072

**Comment by Kevin4ch** [comment]
好的非常感谢 直接删除/dev/ion可以了
