### ISSUE TITLE
为什么不出一个通用的python包呢？？ 

### ISSUE THREAD

**Issue by eyu11** [rockchip-linux/mpp#395]
为什么不出一个通用的python包呢？？ 各种版本折腾～～累

**Comment by HermanChen** [comment]
因为芯片支持和系统环境啥的太复杂了，上面 python 是要以可以写成一样，底下不同环境出的问题千奇百怪
python 是胶水层，用来连接成熟组件可以，解决不了底层问题

**Comment by eyu11** [comment]
可以推荐固定几种芯片及操作系统组合~




饿鱼
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rockchip-linux/mpp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月4日(星期四) 下午2:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rockchip-linux/mpp] 为什么不出一个通用的python包呢？？  (Issue #395)





 
因为芯片支持和系统环境啥的太复杂了，上面 python 是要以可以写成一样，底下不同环境出的问题千奇百怪
 python 是胶水层，用来连接成熟组件可以，解决不了底层问题

**Comment by HermanChen** [comment]
比较难……客户用的实际环境千奇百怪
