### ISSUE TITLE
RK3399设置log2_max_frm_num参数编码数据无法解码显示

### ISSUE THREAD

**Issue by quietInside** [rockchip-linux/mpp#398]
你好，

使用mpi_enc_test.c的测试程序，添加`mpp_enc_cfg_set_u32(cfg, "h264:log2_max_frm_num", 4);`设置参数，将log2_max_frm_num的参数由原本默认的12修改成4。
运行`./mpi_enc_test -w 1920 -h 1080 -t 7 -i ReadySetGo_1920x1080_nv12_200.yuv -o ReadySetGo.h264 -n 150 -f 0`，编码出h264文件，编码过程中未报错，但是无法正常解码显示。

查看其sps信息log2_max_frm_num确实修改成了4
对编码出的h264文件进行分析，slice_header中的frame_num还是按照16位bit进行的编码，解码器解析时却是按照4位bit去解析，导致所以frame_num全部都是0，解码出错。

编码slice时的frame_num是否没有根据log2_max_frm_num修改？

附件为编码出的h264文件
[ReadySetGo.zip](https://github.com/rockchip-linux/mpp/files/11412221/ReadySetGo.zip)

**Comment by HermanChen** [comment]
fixed by f91f152a1a8e5bd95174498c834e7a734e2ce4de
