### ISSUE TITLE
Motion vectors as side data during encoding

### ISSUE THREAD

**Issue by sat8** [rockchip-linux/mpp#4]
Hi

Please confirm if md_buf array in  https://github.com/rockchip-linux/mpp/blob/develop/test/mpi_enc_test.c will be filled with motion vector information after encoding a given frame (h.264 of course ).

Is this buffer exposed up above in mpph264enc gstreamer plugin? Is there any other way I could get this data in gstreamer (sink or shared memory transfer from driver etc.,)

Thnx

**Comment by hizukiayaka** [comment]
I decided to make its as meta data in gstreamer, you should leave a message there not here.
