### ISSUE TITLE
有最新的文档吗

### ISSUE THREAD

**Issue by Nullkooland** [rockchip-linux/mpp#401]
这个库没有像 rga 或者 rknn 那样的详细 API 文档吗？

**Comment by HermanChen** [comment]
网上找下 mpp 开发参考，pdf 的，目前没带在代码库里

**Comment by Nullkooland** [comment]
> 网上找下 mpp 开发参考，pdf 的，目前没带在代码库里

给个地址？就不能上传到这个 repo 吗？

**Comment by HermanChen** [comment]
https://opensource.rock-chips.com/images/b/bf/MPP_%E5%BC%80%E5%8F%91%E5%8F%82%E8%80%83_v0.3.pdf
