### ISSUE TITLE
RK3588 运行 mpp_platform_test 不返回任何信息

### ISSUE THREAD

**Issue by Wunyje** [rockchip-linux/mpp#410]
RK3588 运行 `mpp_platform_test` 不返回任何信息，且运行 `mpi_dec_test` 时，能生成文件但不返回任何信息。

**Comment by HermanChen** [comment]
估计是 linux 平台，export mpp_syslog_perror=1 然后再跑下

**Comment by Wunyje** [comment]
好了，谢谢
