### ISSUE TITLE
mpi_dec_test 无法解码包含B帧的H264流，这个是mpi_dec_test用例不支持还是mpp本身不支持

### ISSUE THREAD

**Issue by mengxing-feng** [rockchip-linux/mpp#414]

**Comment by HermanChen** [comment]
mpi_dec_test 支持 B 帧的 H.264 流啊

**Comment by mengxing-feng** [comment]
在ubuntu下面gstreamer 用x264enc插件编码默认参数带有B帧，送到mpi_dec_test下面无法解码，将x264enc设置为不带B帧的，再用mpi_dec_test就可以

**Comment by HermanChen** [comment]
提供下码流？

**Comment by mengxing-feng** [comment]
暂时找不到那个码流了，又用x264enc生成的默认参数不带B帧了，应该是插件保存了上次的配置，重新配置的生成带B帧的现在mpi_dec_test刚试试又可以解码了，可能那个码流有点问题，上次的码流还用ffmpeg解码都没问题，上次的码流被生成的新文件冲刷掉了，找不到了
