### ISSUE TITLE
将jpg解码成rgb888报错了

### ISSUE THREAD

**Issue by wddnzjwd** [rockchip-linux/mpp#416]
【环境】
芯片：RV1126
系统：Debian

前提：已能正常用mpp将jpg图片解码成默认格式yuv420sp nv12。

需求：现在想要设置解码格式为rgb。 

仅在原有配置上的 ret = mpp_init(ctx, MPP_CTX_DEC, type);后面增加了下面两行：

    MppFrameFormat  format = MPP_FMT_RGB888;
    ret = mpi->control(ctx, MPP_DEC_SET_OUTPUT_FORMAT, &format);

于是在解码时执行到下面这一行报错了：

ret = mpi->poll(ctx, MPP_PORT_OUTPUT, MPP_POLL_BLOCK);

错误信息：

<img width="421" alt="1689157909005_26219720-EB44-4db8-AF28-6DB5FFA502DB" src="https://github.com/rockchip-linux/mpp/assets/115400478/c5adc308-38b6-43f5-821f-60db013b0d54">

解码时的完整方法：
void MppDecoder::DecoderJpeg(unsigned char* buff, int64_t buffsize) {
    MPP_RET ret = MPP_OK;
    RK_U8* buf = data.buf;
    MppPacket packet = data.packet;
    MppFrame  frame = data.frame;
    MppTask task = NULL;

    memcpy(buf, buff, buffsize);
    // reset pos
    mpp_packet_set_pos(packet, buf);
    mpp_packet_set_length(packet, buffsize);
    mpp_packet_set_eos(packet);

    mpp_err("pppppp ctx=%p mpi=%p frame=%p\n", ctx,mpi, frame);

    ret = mpi->poll(ctx, MPP_PORT_INPUT, MPP_POLL_BLOCK);
    if (ret) {
        mpp_err("%p mpp input poll failed\n", ctx);
        return;
    }

    ret = mpi->dequeue(ctx, MPP_PORT_INPUT, &task);  /* input queue */
    if (ret) {
        mpp_err("%p mpp task input dequeue failed\n", ctx);
        return;
    }

    mpp_assert(task);

    mpp_task_meta_set_packet(task, KEY_INPUT_PACKET, packet);
    mpp_task_meta_set_frame(task, KEY_OUTPUT_FRAME, frame);
    printf("%s, %d\n", __func__, __LINE__);
    ret = mpi->enqueue(ctx, MPP_PORT_INPUT, task);  /* input queue */
    printf("%s, %d\n", __func__, __LINE__);
    if (ret) {
        mpp_err("%p mpp task input enqueue failed\n", ctx);
        return;
    }
    printf("%s, %d\n", __func__, __LINE__);

    /* poll and wait here */
    mpp_err("pppppp ctx=%p mpi=%p frame=%p\n", ctx, mpi, frame);
    ret = mpi->poll(ctx, MPP_PORT_OUTPUT, MPP_POLL_BLOCK);
    printf("%s, %d\n", __func__, __LINE__);
    if (ret) {
        mpp_err("%p mpp output poll failed\n", ctx);
        return;
    }
    printf("%s, %d\n", __func__, __LINE__);

    ret = mpi->dequeue(ctx, MPP_PORT_OUTPUT, &task); /* output queue */
    printf("%s, %d\n", __func__, __LINE__);
    if (ret) {
        mpp_err("%p mpp task output dequeue failed\n", ctx);
        return;
    }
    printf("%s, %d\n", __func__, __LINE__);
    mpp_assert(task);
    printf("%s, %d\n", __func__, __LINE__);

    if (task) {
        MppFrame frame_out = NULL;
        mpp_task_meta_get_frame(task, KEY_OUTPUT_FRAME, &frame_out);
        //mpp_assert(packet_out == packet);

        if (frame) {

            if (mpp_frame_get_eos(frame_out))
                mpp_log("%p found eos frame\n", ctx);
        }
        /* output queue */
        ret = mpi->enqueue(ctx, MPP_PORT_OUTPUT, task);
        if (ret)
            mpp_err("%p mpp task output enqueue failed\n", ctx);
    }
}

请问是否支持将jpg直接解码成rgb888呢？还是哪里配置出问题了呢？
但是jpg解码成yuv420sp nv12是正常的，就只增加了2行配置想直接解码成rgb888就不行了。

**Comment by HermanChen** [comment]
https://github.com/rockchip-linux/mpp/blob/62922f3cc1b416e1a9444e75759bd8d8dd2340e1/osal/mpp_soc.cpp#L742
参考这里，1126 的 jpeg 解码器是没有 pp 功能的，也就是没有带格式转换功能，所以配置 output format 会失败
