### ISSUE TITLE
MPP_ERR_BUFFER_FULL

### ISSUE THREAD

**Issue by saokuazi** [rockchip-linux/mpp#427]
您好，在使用MPP硬件解码长时间运行的情况下，出现ret = mpi->decode_put_packet(ctx, packet)执行失败，返回MPP_ERR_BUFFER_FULL，卡在循环中，视频中断，请问这种情况该如何处理。
![52cbc0c488d1de68f2dd73a6d3d315c](https://github.com/rockchip-linux/mpp/assets/32724327/461e92c7-3861-4e6c-9432-6a638d3ccb7c)

**Comment by HermanChen** [comment]
这种情况比较常见是图像没有及时取走，输出队列满了，还有可能是图像 buffer 有泄漏，分不出来内存，内部解码线程卡住，输入端也就送不进去了。

**Comment by HermanChen** [comment]
把环境变量 mpp_dec_debug 配置为 0x10 然后跑，看最后 log 停在什么状态下
安卓下 setprop mpp_dec_debug 0x10
linux下 export mpp_dec_debug=0x10

**Comment by saokuazi** [comment]
> 把环境变量 mpp_dec_debug 配置为 0x10 然后跑，看最后 log 停在什么状态下 安卓下 setprop mpp_dec_debug 0x10 linux下 export mpp_dec_debug=0x10

您好，尝试了该方法。程序卡在mpp[13037]: mpp_log: decode put packet failed. -1012。
![fd4a37296b5213edf4b169bcf4278e2](https://github.com/rockchip-linux/mpp/assets/32724327/5d170b00-e3b7-45b3-86c1-a61f54940735)

**Comment by HermanChen** [comment]
不是，要看 check_task_wait 的内部等待停在哪里了，看 0x200 的等待看起来是等待前一个任务完成，是不是内核驱动有报错出来，建议看下串口的 log

**Comment by walletiger** [comment]
遇到 相同 问题， 输入数据有丢包，就容易出现， 楼主解决了吗？

**Comment by HermanChen** [comment]
输出数据有及时取走，就不会出问题

**Comment by walletiger** [comment]
> 输出数据有及时取走，就不会出问题

取走了， 更新 了最新版本 mpp 解决了
