### ISSUE TITLE
MPP解码数据格式问题

### ISSUE THREAD

**Issue by Ryan3812** [rockchip-linux/mpp#434]
使用MPP解码出来数据只能为支持YUV420SP格式吗，还是能支持其他数据格式，能的话可以支持哪些格式

**Comment by HermanChen** [comment]
除了 jpeg 解码可以选择输出格式，其他解码都只有 YUV420SP

**Comment by Ryan3812** [comment]
好的，感谢回复。我想问下其他解码出来数据只能支持YUV420SP是由什么原因引起的，是硬件电路或者是驱动还是其他原因呢

**Comment by HermanChen** [comment]
硬件设计如此
