### ISSUE TITLE
MPP支持更多码率控制相关的参数吗？

### ISSUE THREAD

**Issue by yun-ling** [rockchip-linux/mpp#438]
我们已经接入MPI接口，码率控制模式现在只有CBR 、VBR、AVBR。
我们希望在动态画面的时候，可以自动降低码率，牺牲画质保证码率需求，同时在静态画面的时候，降低QP以提升画质。现在没有办法找到对应的配置项可以支持这样的配置，码率控制的模式也比较有限，有什么还没有暴露出来的隐藏字段吗

**Comment by yun-ling** [comment]
有没有全面的H264/H265 的控制参数？

**Comment by HermanChen** [comment]
参考 mpi_enc_test，码率，qp 的接口都有，具体参数名称在 mpp_enc_cfg.cpp 的表格里

**Comment by yun-ling** [comment]
运动补偿的相关参数似乎没有开放出来，比如前向参考的帧数，这个对运动画面的画质和码率有显著的优化

**Comment by HermanChen** [comment]
硬件编码器一般固定单参考前一帧，不像软件编码器那么灵活

**Comment by yun-ling** [comment]
了解，感谢解答

**Comment by yun-ling** [comment]
另外， mpp_enc_cfg.cpp 里的参数可供选择的值可以提供一下吗？每一个参数的含义有进一步的解释吗？

**Comment by HermanChen** [comment]
哦，这个得看以后的文档更新了……目前只能死看代码了。。。。
