### ISSUE TITLE
解码器调用mpp_destroy(_decoder.ctx)崩溃

### ISSUE THREAD

**Issue by zhang-chuanfeng** [rockchip-linux/mpp#439]
关闭解码器调用mpp_destroy接口崩溃。
![image](https://github.com/rockchip-linux/mpp/assets/59160162/e57962a9-958e-467e-aa2c-f4628a942964)

**Comment by Kevin4ch** [comment]
怎么解决的兄弟？同样的错误

**Comment by Liaoyyyy** [comment]
您好，我们这边没能成功复现，该问题为偶发还是必然？请问能否提供更多信息（如测试数据，芯片和系统平台信息）以帮助我们复现问题？

**Comment by Liaoyyyy** [comment]
经过测试验证，发现一个可能导致mpp_destory过程导致崩溃的问题，可使用这个补丁解决
[458[git]_mpp_destory.patch](https://github.com/rockchip-linux/mpp/files/13039791/458.git._mpp_destory.patch)

**Comment by Liaoyyyy** [comment]
按照我们建议的开发流程，mpp_destroy前需调用mpi->reset(ctx)确保将相关资源重置，是不会出现该类crash的。相关实现细节可参考test/mpi_dec_test.c与test/mpi_enc_test.c
