### ISSUE TITLE
RV1126 mpp_vdpu2 报错

### ISSUE THREAD

**Issue by wddnzjwd** [rockchip-linux/mpp#442]
请问一下各位：

1.芯片型号： RV1126
2.系统环境：
armv7
Linux 4.19.111 #245 SMP PREEMPT Fri Jul 1 11:33:47 CST 2022 armv7l GNU/Linux
3.项目的业务流程是：接入摄像头的流，然后每隔一段时间进行抽帧，接着将图片进行硬件解码和编码。 当接入10路rtsp流运行大概半小时左右系统会出现自动重启现象。 请问有谁知道这是什么原因吗？
抽帧解码时的报错日志如下：

![image](https://github.com/rockchip-linux/mpp/assets/115400478/9bb17718-eae2-4a5b-a72f-bd1768435161)

**Comment by HermanChen** [comment]
寄存器 64 是输入码流地址，看报错是码流地址读取异常了，可能是码流 buffer 被应用给释放掉
