### ISSUE TITLE
关于判断IDR帧或KeyFrame

### ISSUE THREAD

**Issue by zhangjp0405** [rockchip-linux/mpp#447]

**Comment by zhangjp0405** [comment]
请问在使用MPP编码库的时候怎么判断编码后的帧是KeyFrame帧(I帧)

**Comment by HermanChen** [comment]
输出的 pkt 去 get meta，里有个 KEY_OUTPUT_INTRA 的 key，可以用来判断是不是 I 帧

**Comment by zhangjp0405** [comment]
好滴，感谢作者的提示




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Herman ***@***.***&gt;; 
发送时间: 2023年9月28日(星期四) 下午4:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [rockchip-linux/mpp] 关于判断IDR帧或KeyFrame (Issue #447)





 
输出的 pkt 去 get meta，里有个 KEY_OUTPUT_INTRA 的 key，可以用来判断是不是 I 帧

**Comment by zhangjp0405** [comment]
想再请教下，怎么释放MppApi*指针所指对象的资源，可以手动用"delete MppApi*"指针语句这样释放资源吗，还是说只要用"mpp_destroy(m_pMppCtx)"语句来释放MppCtx即可
