### ISSUE TITLE
3568如何修改编码器频率提高编码性能

### ISSUE THREAD

**Issue by zhang-chuanfeng** [rockchip-linux/mpp#449]
你好  想咨询下如何提高3568  264编码器性能。目前测试1080p 25帧编码 最大只能到4路。
我看历史issue有提高编码器性能，通过改变硬件编码器频率，系统中并未找到。

**Comment by HermanChen** [comment]
3568 的标称规格只有 1080p@60fps，再往上的性能是不保证的，提频需要芯片工艺支持和 IC  signoff 频率支持，各个芯片的超频能力是不一样的，3568 基本没得超频
