### ISSUE TITLE
编译deb，失败。

### ISSUE THREAD

**Issue by yhsilience** [rockchip-linux/mpp#45]
cmake = 3.52 
在rk3399 debian文件系统中编译
注释掉 
# This is example for Cmake (See http://bugs.debian.org/641051 )
override_dh_auto_configure:
	dh_auto_configure -- \
//	-DCMAKE_TOOLCHAIN_FILE=/etc/dpkg-cross/cmake/CMakeCross.txt \
	-DCMAKE_BUILD_TYPE=Release \
	-DRKPLATFORM=ON \
	-DHAVE_DRM=ON \
	-DARM_MIX_32_64=ON

DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -rfakeroot -b -d -uc -us -aarmhf

最后出现

dh_install: cannot run debian/librockchip-mpp-dev.install: No such file or directory
debian/rules:21: recipe for target 'binary' failed
make: *** [binary] Error 2
该怎么解决呢？？？

**Comment by JeffyCN** [comment]
fixed
