### ISSUE TITLE
MPP解码task模式如果需要2个或者多个packet才能产生一个frame的话，什么方式来调用这个接口呢

### ISSUE THREAD

**Issue by CCcooode** [rockchip-linux/mpp#450]
![image](https://github.com/rockchip-linux/mpp/assets/106292555/baa93158-ce81-48a2-b6dc-472a1d6706d6)
按照示例代码里面的，必须是一个packet产生一个frame，不然poll就卡住了，
如果需要多个packet ，怎么塞入更多的packet呢

**Comment by HermanChen** [comment]
不会的，port 有队列数量，使用 split 模式，就可以多包出一帧

**Comment by CCcooode** [comment]
> 不会的，port 有队列数量，使用 split 模式，就可以多包出一帧

![image](https://github.com/rockchip-linux/mpp/assets/106292555/7308fc5d-1683-4877-b48f-c91bae5aec73)
![image](https://github.com/rockchip-linux/mpp/assets/106292555/5445412c-d44a-4722-babc-58296cff9412)
我是用的split 模式，同样4个packet，用put_packet/get_frame接口就可以正常出帧，用task模式就poll卡住，是我的用法有问题么
