### ISSUE TITLE
VDPU381 vp9 capabilities

### ISSUE THREAD

**Issue by hbiyik** [rockchip-linux/mpp#452]
i am using rk3588 with vdpu381 dual core decoder.
There is below info about the capabilities, but i think this is wrong it can normally max out at 30fps with 8k inputs. Am i correct? This seems to be wrong.
![image](https://github.com/rockchip-linux/mpp/assets/24766436/4f991caa-3da8-4006-a89c-48a4a5122fcb)

**Comment by hbiyik** [comment]
Also H264 decoder on vdpu381 has the same 1600MBps bitrate and it is 8K@30
Only hevc is 2133mbps and it is 8K@60.

**Comment by HermanChen** [comment]
Yes, you are right. The h.264 and vp9 performance is half of h.265 performance.

**Comment by hbiyik** [comment]
Thanks
