### ISSUE TITLE
mpp_destroy 崩溃

### ISSUE THREAD

**Issue by Kevin4ch** [rockchip-linux/mpp#458]
![image](https://github.com/rockchip-linux/mpp/assets/8243696/223cb648-f07a-49ed-97c5-b6afb73af5f5)

**Comment by HermanChen** [comment]
Any more log? It is 100% reproduce?

**Comment by Liaoyyyy** [comment]
您好，我们这边没能成功复现，该问题为偶发还是必然？请问能否提供更多信息（如出错的码流，芯片和系统平台信息）以帮助我们复现问题？

**Comment by Liaoyyyy** [comment]
经过测试验证，发现一个可能导致mpp_destory过程导致崩溃的问题，可使用这个补丁解决

[458[git]_mpp_destory.patch](https://github.com/rockchip-linux/mpp/files/13039763/458.git._mpp_destory.patch)

**Comment by Liaoyyyy** [comment]
按照我们建议的开发流程中，mpp_destroy前需调用mpi->reset(ctx)确保将相关资源重置，是不会出现该类crash的。相关实现细节可参考test/mpi_dec_test.c与test/mpi_enc_test.c
