### ISSUE TITLE
mpi_dec_test.c测试用例文件读取疑问

### ISSUE THREAD

**Issue by xueshenan** [rockchip-linux/mpp#460]
Hi, ，我尝试了下[mpi_dec_test](https://github.com/rockchip-linux/mpp/blob/develop/test/mpi_dec_test.c#L96)测试用例，有如下疑问咨询下：
问题 1 :
mpi_dec_test每次从文件读取都是4096个字节，然后封装为packet。
```c
    // when packet size is valid read the input binary file
    ret = reader_read(cmd->reader, &slot);

    mpp_packet_set_data(packet, slot->data);
    mpp_packet_set_size(packet, slot->size);
    mpp_packet_set_pos(packet, slot->data);
    mpp_packet_set_length(packet, slot->size);        // size always be 4096

  ret = mpi->decode_put_packet(ctx, packet);

 ret = mpi->decode_get_frame(ctx, &frame);      // 可以正常获取解码数据
```

h264每个分片肯定不是确定的4096个字节，但是发给解码器后却可以正常输出yuv数据，所以mpp会自动进行数据包的合并和切割操作了?

问题2

我尝试了移植mpp解码器用于解码rtp视频流，但是调用mpi->decode_get_frame，frame总是空的，没有帧输出，返回值提示是SUCCESS，请问如何输出更详细的出错信息，现在是没有任何错误信息的，很难调试。 码流已经用ffmpeg avcodec解码成功过。

**Comment by HermanChen** [comment]
1. 有配置解码器 base:split_parse 为 1，表示解码器进行内部分帧操作
2. 返回 MPP_OK 表示流程正常，没有问题，frame 为空表示没有取到图像数据，也是正常的，解码报错的话，出错信息在 MppFrame 的 errInfo 里
