### ISSUE TITLE
RKMPP解码B帧, 需要用户自己手动排序?

### ISSUE THREAD

**Issue by lion117** [rockchip-linux/mpp#464]
# 背景
1. RK3399 
2. AARCH64-KYLIN
3. 视频文件为1080P的3B-1P模式的H264文件
4. 输入解码的pts, dts均为0 
5. 解码后的YUV数据直接保存到本地

# 现象
1. 打开NV12数据, 视频在鬼畜的跳动

# 问题
> RKMPP解码带B帧的视频, 解码器是否有参数设置解码器内部实现显示序列排序吗? 还是需要用户在外部手动排序实现显示序列?

**Comment by HermanChen** [comment]
默认情况下，mpp 会使用显示序输出 YUV，但是是开了 IMMEDIATE_OUT 的情况下，会用解码序输出，请检查下解码器的配置

**Comment by chness97** [comment]
![Image](https://github.com/user-attachments/assets/cdb42667-52ab-4020-9571-3d81787625f3)sort-pts源代码默认是0，表示不排序，请问如何才能显示序输出（排序后的顺序）？
