### ISSUE TITLE
最新的Android demo有吗？

### ISSUE THREAD

**Issue by yu12mang** [rockchip-linux/mpp#468]
最新的Android demo有吗？我编译了so库  替换了这个项目的so库和include文件 https://github.com/c-xh/RKMediaCodecDemo   运行后各种报错!

**Comment by yu12mang** [comment]
`../../../../src/main/jniLibs/arm64-v8a/libmpp.so: error adding symbols: File in wrong format`

**Comment by HermanChen** [comment]
这个log是格式不对啊？工具链不匹配？
