### ISSUE TITLE
file handle leak causeed memory leak

### ISSUE THREAD

**Issue by wshyu** [rockchip-linux/mpp#47]
MPP decoded video stream from WFD of APPLE's device, memory leak arise while APPLE's video resolution changed.

below is screenshot for this issue:

![_20180709174023](https://user-images.githubusercontent.com/40785388/42443133-3d8ad028-839f-11e8-9905-80e1d943e330.png)

**Comment by HermanChen** [comment]
Can you use mpi_dec_test to decode the raw video stream to check whether this issue happen on the unit test?

**Comment by wshyu** [comment]
mpi_dec_test only cloud be read video stream from file and would be exit after compelete decoding file.
while mpi_dec_test  or our app exits, memory or file handle would be recycled.
