### ISSUE TITLE
RK3588上调用mpi_dec_test失败（基于官网Ubuntu20系统）

### ISSUE THREAD

**Issue by shiqifeng2000** [rockchip-linux/mpp#475]
rk3588开发板，刷了官网[3588J](https://www.t-firefly.com/doc/download/160.html)上的Ubuntu20, 下载mpp最新代码（develop分支），使用develop分支编译后调用无响应，切到的release，在build/linux/aarch64中执行make-Makefiles.bash && make -j 操作后

检查环境
![1](https://github.com/rockchip-linux/mpp/assets/9416410/dfca63e2-3080-4e41-82f8-cef061a61b96)

检查视频（h264, annexb）
![2](https://github.com/rockchip-linux/mpp/assets/9416410/7071d4e8-84f4-4ffb-9bdb-5ae0252cb068)

调用mpi_dec_test
![3](https://github.com/rockchip-linux/mpp/assets/9416410/1f7e9e0a-aef0-4831-86f1-5a61007a3016)

结果显示
![4](https://github.com/rockchip-linux/mpp/assets/9416410/8f11df8b-03db-4e47-bb36-cdfb03fa2f54)

原视频截图
![Screenshot from 2023-11-21 08-58-53](https://github.com/rockchip-linux/mpp/assets/9416410/b585264c-002d-4242-aee7-4218df569d66)

**Comment by FumasterLin** [comment]
release分支已经很久没有维护了，请使用develop分支

**Comment by shiqifeng2000** [comment]
> release分支已经很久没有维护了，请使用develop分支

![Screenshot from 2023-11-21 09-51-42](https://github.com/rockchip-linux/mpp/assets/9416410/dd4307d4-4648-4da6-b6b5-cb5520b46351)

使用develop分支是无响应才切到的release

**Comment by FumasterLin** [comment]
默认log是输出到sys了，export mpp_syslog_perror=1

**Comment by shiqifeng2000** [comment]
> 默认log是输出到sys了，export mpp_syslog_perror=1

设置后再次执行
![6](https://github.com/rockchip-linux/mpp/assets/9416410/cb7c8efc-d0a4-469c-ad0c-3d222f7d5aa7)

**Comment by FumasterLin** [comment]
用root权限执行看下

**Comment by shiqifeng2000** [comment]
> 用root权限执行看下

![7](https://github.com/rockchip-linux/mpp/assets/9416410/18a350a5-2a6f-4d1a-945b-5e50317e5508)

![8](https://github.com/rockchip-linux/mpp/assets/9416410/ee78aae8-9f07-49ea-92af-5a88b36f1dc0)

可以了，不过好像不是yuv420p，用nv12貌似正确，请问解码默认输出nv12么

**Comment by FumasterLin** [comment]
是的 默认输出nv12

**Comment by shiqifeng2000** [comment]
> 是的 默认输出nv12

-f 参数如何调整输出格式呢，我尝试 yuv420p, 数字4, 都不行，结果都是nv12

**Comment by FumasterLin** [comment]
这个不支持配置输出格式哦

**Comment by shiqifeng2000** [comment]
> 这个不支持配置输出格式哦

了解，谢谢
