### ISSUE TITLE
mpp指定哪几路解码流

### ISSUE THREAD

**Issue by wzjmail** [rockchip-linux/mpp#476]
如何指定使用哪几路解码流，gpt给的答案如下，在mpp源码中没有找到MPP_PARAM_DEC_STREAM_INDEX，请问有这个实现么，现在的参数是什么
【
// 指定使用哪几路解码
    int targetDecStreamIndexes[] = {0, 2};  // 指定使用第0和第2路解码
    param = {MPP_CTX_DEC, MPP_PARAM_DEC_STREAM_INDEX, targetDecStreamIndexes};
    mpp_ioctl(decoder_ctx, MPP_IOC_SET_OUTPUT_BLOCK, &param);
】

**Comment by wzjmail** [comment]
MPP_IOC_SET_OUTPUT_BLOCK  同样也没有找到

**Comment by HermanChen** [comment]
gpt 不能全信，看代码才是可靠的……
