### ISSUE TITLE
about decode jpeg from rkmedia vi

### ISSUE THREAD

**Issue by docterling** [rockchip-linux/mpp#482]
my sdk version is rv1126-rv1109 V2.2.5
i had used rkmedia's vi api to capture usb camera's mjpeg,i had checked the saved file it look's ok.
i referred to mpi_dec_test.c,jpeg decode use dec_advanced,here is my decode chain
capture thread:
RK_MPI_SYS_GetMediaBuffer get MEDIA_BUFFER and put it to list
decode thread:
get MEDIA_BUFFER mb from list,and the decoder api needs MppPacket,i use mpp_packet_init(&packet, RK_MPI_MB_GetPtr(mb), RK_MPI_MB_GetSize(mb))
but it return errors:
`mpp[924]: mpp_packet: check_is_mpp_packet pointer 0x9f50b470 failed on check`
`mpp[924]: mpp_dec: mpp_dec_advanced_thread line(1452): Error! Get no buffer from input packet`
yeah,it must use MppBuffer to init the MppPacket,is that right?
if it's,how can i covert MEDIA_BUFFER to MppBuffer

**Comment by HermanChen** [comment]
rkmedia is not maintained any more. We turn to rockit now on latest sdk.
It better to switch to new middleware.
About the MppPacket and MppBuffer they are independent to each other. MppPacket can use a malloc buffer.

**Comment by docterling** [comment]
thank you for the info

**Comment by smzahraee** [comment]
is the rockit open source?
where can I download it?
