### ISSUE TITLE
mpp硬解码如何指定通道

### ISSUE THREAD

**Issue by wzjmail** [rockchip-linux/mpp#484]
1. mpp硬解视频，多进程并行，不会冲突，会做串行化处理，是有什么前提条件么。
目前遇到的情况是和合作商各有一个mpp硬解进程。一个使用mpi封装好的接口，看了文档底层也是mpp；另一个进程直接使用mpp; 请问这种情况会冲突么

2. 目前合作商使用的mpi指定使用第0路。我的理解进程直接使用mpp,未进行指定，也应该使用默认的0路。会冲突么
3. 如果mpp想指定通道，指定接口可以指导下么
目前使用的是：

#include "mpp_mem.h"
#include "mpp_env.h"
#include "mpp_time.h"
#include "mpp_common.h"

mpp_create(&decoder_ctx, &decoder_mpi);
mpp_init(decoder_ctx, MPP_CTX_DEC,type);
 MPP_RET ret = decoder_mpi->decode_put_packet(decoder_ctx, packet);
decoder_mpi->decode_get_frame(decoder_ctx, &frame)
mpp_frame_get_buffer(frame)

**Comment by HermanChen** [comment]
第几路这个是逻辑上的通路吧，mpp 的设备是为了单个物理通路可以虚拟出无数个逻辑通路来设计的，所以没有绑定物理通路的方式，同时芯片一般只有一个编解码一个解码，定物理通路没有什么意义

**Comment by HermanChen** [comment]
要指定通道的话，把 MppCtx 和通道号做绑定即可，做一个中间层转换一下

**Comment by wzjmail** [comment]
> 要指定通道的话，把 MppCtx 和通道号做绑定即可，做一个中间层转换一下
目前看RKMedia-api 封装好的api中是有指定通道的实现，也是按照您上面说的这种思路做的么。只是底层mpp如果想指定，需要自行实现是么
```
#函数定义：
RK_S32 RK_MPI_VDEC_CreateChn(VDEC_CHN VdChn, const VDEC_CHN_ATTR_S *pstAttr);
# VdChn 为解码通道号； pstAttr 为解码通道属性指针。
#使用示例：
RK_MPI_VDEC_CreateChn(stVdecChn.s32ChnId, &stVdecAttr);
```

**Comment by wzjmail** [comment]
mpp默认是单通道解码么，默认为0？

**Comment by HermanChen** [comment]
硬件只有一个，时分复用的

**Comment by wzjmail** [comment]
您好，您的意思是在同一个进程中即便是指定多通道，实际也是多通道串行交替在解码吧。

但是我现在遇到的问题是，单进程mpp硬解码没有问题，而两个进程同时mpp硬解会卡住或者崩溃。

崩溃直接卡在mpi获取解码图片这里，media_buffer为NULL;

所以想看下两个进程分别指定不一样的通道，会不会不冲突。但是现在mpp没有现成的指定通道的实现是么，需要自己搞？



> 硬件只有一个，时分复用的

**Comment by wzjmail** [comment]
![Uploading 崩溃位置.png…]()

**Comment by HermanChen** [comment]
用 mpi_dec_test 做测试，正常不应该出现问题，有出现问题的话，比较大可能是内核驱动的版本问题，升级下就好

**Comment by wzjmail** [comment]
> 用 mpi_dec_test 做测试，正常不应该出现问题，有出现问题的话，比较大可能是内核驱动的版本问题，升级下就好

目前怀疑是mpp接口占用了默认通道0。 而rkmedia_api 作为底层接口，留了指定通道配置参数，设置为0。  在新跑程序时，两个进程并行，但是mpp程序先占用了通道0。导致rkmedia_api进程无法使用指定0通道，导致冲突。

1. 想问下目前mpp可以指定通道，比如通过传参或者写到配置项中，类似这种mpp_dec_cfg_set_u32(cfg, "base:split_parse", need_split);
2.  如果没有，想问下除了改用底层rkmedia_api 接口外，【要指定通道的话，把 MppCtx 和通道号做绑定即可，做一个中间层转换一下】这个具体该怎么实现

**Comment by HermanChen** [comment]
rkmedia 接口后面不再维护了，最好能升级成使用 rockit 接口
