### ISSUE TITLE
请教如何正确编译Android mpp库？

### ISSUE THREAD

**Issue by wentaitu** [rockchip-linux/mpp#485]
#### 1.根据文档5.2节
> 5.2 编译
MPP源代码编译脚本为cmake，需要依赖2.8.12以上的版本，建议使用2.8.12版，使用高版本的cmake工具可能会产生较多的warning。
5.2.1 Android平台交叉编译
编译Android库需要使用ndk环境，默认脚本使用android-ndk-r10d进行编译。
r10d ndk的下载路径可以在源代码目录下的build/android/ndk_links.md文件里查找。
把下载好的ndk解压到/home/pub/ndk/android-ndk-r10d，或者手动修改build/android/目录下env_setup.sh脚本的ANDROID_NDK变量路径。
进入build/android/arm/目录，运行make-Android.bash脚本生成编译用Makefile，运行make –j16进行编译。
#### 2.尝试编译后报错
(1)clone源码后修改mpp/build/android/aarch64/make-Android.bash，添加如下两行
ANDROID_NDK=/usr/ndk/android-ndk-r16b/
CMAKE_PROGRAM=/usr/local/bin/cmake
(2)执行`virtual-machine:~/mpp/build/android/aarch64$ ./make-Android.bash`报错
```
../env_setup.sh: 行 2: $'\r': 未找到命令
../env_setup.sh: 行 7: 未预期的符号 `$'in\r'' 附近有语法错误
'./env_setup.sh: 行 7: `    case $1 in
-- cmake version 3.21.3
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/home2/wttu/mpp/CMakeFiles/CMakeOutput.log".
See also "/home2/wttu/mpp/CMakeFiles/CMakeError.log".
No such file or directory
CMake Error: Generator: execution of make failed. Make command was:  -f Makefile -j &&
```
请教正确的步骤和命令应该是什么

**Comment by HermanChen** [comment]
文档更新得比较慢……
cmake 用新版本的也没问题，我们目前用 3.12 没问题，ndk 现在推荐用 r16d 了

**Comment by wentaitu** [comment]
我的cmake version 3.21.3，ndk version r16b，修改了mpp/build/android/aarch64/make-Android.bash添加如下两行
ANDROID_NDK=/usr/ndk/android-ndk-r16b/
CMAKE_PROGRAM=/usr/local/bin/cmake
然后执行运行bash脚本，这样的步骤正确吗？还有其它步骤吗

看其它人有这样的步骤？不过我运行后仍然报错
```
$ git clone https://github.com/rockchip-linux/mpp.git
$ cd mpp
$ git checkout -b test-branch fb73f23f53
$ cmake -DRKPLATFORM=ON -DHAVE_DRM=ON
$ make -j4
$ sudo make install
```
报错如下：
```
mpp/osal/mpp_dmabuf.cpp:9:27: fatal error: linux/dma-buf.h: 没有那个文件或目录
 #include <linux/dma-buf.h>
```

**Comment by HermanChen** [comment]
把 build/android/aarch64 目录下的 CMakeCache.txt 删一下，定义好 ndk 路径即可
dma-buf.h 没有的问题，我更新下，新补丁已经解决了

**Comment by wentaitu** [comment]
tks
