### ISSUE TITLE
sharpen & denoise on h264 encoding

### ISSUE THREAD

**Issue by diegonieto** [rockchip-linux/mpp#486]
Does the `sharpen` and `denoise` settings work? I am not able to see them being used in the tests. This is for Rockchip RK3566.

I am currently trying to make the `MppEncPrepSharpenCfg` work, but so far I don't see any difference in the h264 encoding streams.

Can you help, please?

**Comment by HermanChen** [comment]
Only some old chip can support this feature. So it is not used any more.
