### ISSUE TITLE
咨询Bayer格式的视频如何使用MPP Encoder进行编码？

### ISSUE THREAD

**Issue by eddyli5** [rockchip-linux/mpp#487]
RK3588，使用USB外接工业摄像头，摄像头输出的视频是BayerRG8 格式的，我看目前MppFrame支持的Format没有Bayer相关格式的，想问一下有没有什么比较高效的方法能完成对Bayer格式的视频压缩。谢谢！

**Comment by HermanChen** [comment]
BayerRGB 格式的数据要过下 ISP 才能变成 YUV 的格式，mpp 里做不了这个处理，3588 的硬件上也没有直接压缩 Bayer 格式的编码器……

**Comment by eddyli5** [comment]
未来有可能考虑增加Bayer 格式的编码器吗？

**Comment by HermanChen** [comment]
太小众了……暂时没看到嵌入式平台上的使用场景，可能手机上和广播录制才会用吧？
你们是用在什么地方？

**Comment by eddyli5** [comment]
我们在做一个多目拼接的项目，相机的分辨率都是4K的，所以想尽可能减少输入码流，所以把相机的格式设置为了Bayer的。现在拼接处理完了后还得转码成支持的格式才能压缩，效率就低了。

**Comment by HermanChen** [comment]
一较都是用 ISP 转 Bayer 到 YUV，然后 YUV 上拼接，最后再编码的
