### ISSUE TITLE
rga_mm: RGA_MMU unsupported memory larger than 4G! (当我们使用 libgstrockchipmpp.so 时)

### ISSUE THREAD

**Issue by bluesky2319** [rockchip-linux/mpp#493]
在我的 RK3588 视频转码应用程序中，当转码任务被终止时，重新启动任务后，我看到了此错误。

![a2941fb0c25405d062d7c50d5a2b1f2](https://github.com/rockchip-linux/mpp/assets/98977472/753cebe7-1b2b-49db-a756-164052feb7ef)

因为在我的应用程序中，我使用“libgstrockchipmpp”并且不直接使用RGA，所以很难知道并解决问题的根源。 另外，我的系统内存使用量约为 1.5 GB； 我的有效负载并不多，以至于硬件编码不支持它，就像 2K 分辨率的两个任务一样。 当我看到这个错误时，大多数情况下，转码后的视频没有问题。 我的 libgstrockchipmpp 基于 2021 年 5 月 20 日构建，大约 100 KB。

通常，在不终止任务的情况下，即使负载较高，我也看不到问题。 我该如何解决这个问题？

**Comment by HermanChen** [comment]
rga2 只支持 4G 内的空间，那 mpp 的 MppBufferGroup 在申请的时候需要加个 DMA32 的标志

**Comment by bluesky2319** [comment]
是的，它是 32 位并支持 4GB，但就我而言，它低于此，并且我的最大缓冲是 30 帧。 那么，我们需要在 MPP 或 libgstrockchipmpp 中更改它吗？ 据我所知，libgstrockchip使用librockchip_mpp。 我使用了 libgstrockchimpp 的预构建版本。 您能分享一些相关细节吗？

**Comment by HermanChen** [comment]
目前没有全局配置的方法，还得手工修改代码。。。

**Comment by bluesky2319** [comment]
手动应用它会产生什么后果？ 我的意思是，它会影响其他部分吗？

**Comment by HermanChen** [comment]
没什么影响

**Comment by bluesky2319** [comment]
好，谢谢

**Comment by MattiaGrigoli** [comment]
how and where i have to add this dma flag in the code?
also, is the code of the repo or the code of my application?
