### ISSUE TITLE
Hardware based scaler

### ISSUE THREAD

**Issue by sat8** [rockchip-linux/mpp#5]
Hi

I wonder if a hardware based scaler is available in mpp. My use case is to decode a HD stream and then run some analysis on down scaled raw frame. I see that there is an abandoned ffmpeg repo here. Did it use hardware resizer in any way? 

Thnx

**Comment by hizukiayaka** [comment]
Only JPEG supports it now.

**Comment by HermanChen** [comment]
About this question we plan to add post-process module into mpp. It will come later this year.

**Comment by sat8** [comment]
thnx for the update.

**Comment by zillevdr** [comment]
> About this question we plan to add post-process module into mpp. It will come later this year.__

Include this an deinterlacer?

**Comment by WainDing** [comment]
yes， post-process abort deinterlace will come later.

**Comment by Adam-Langley** [comment]
Hi,

How is porting the hardware scaler to the HD/H264 decoder coming along?

Thanks,
