### ISSUE TITLE
decode_get_frame frame为空

### ISSUE THREAD

**Issue by xiaogao22** [rockchip-linux/mpp#500]
ffmpeg+mpp解海康的摄像头ok，h264/h265都正常，不过换了别的厂家的摄像头，h264解码失败，ffmpeg可以获取流信息，但是decode_get_frame 获取的frame为空，这是什么原因呢？

**Comment by HermanChen** [comment]
ffmpeg 已经因为版权原因不再官方支持了，解码不了的问题可能是分帧异常，可以把码流存下来，给 mpi_dec_test 直接解码看看
