### ISSUE TITLE
视频解码不能获取sei的user_data

### ISSUE THREAD

**Issue by xiayu0101** [rockchip-linux/mpp#504]
您好，我将test目录下的mpi_enc_test.c中user_data_enable设置为1（mpp_env_get_u32("user_data_enable", &p->user_data_enable, 1)）;使用mpp_meta_set_ptr将user_data写入sei帧中，这样我就得到了插入sei帧的h264视频，我使用十六进制查看h264文件看到了我加入的string，同时我使用ffmpeg也看到了这个string的ascii码，但是使用test下mpi_dec_test.c来解析生成的h264视频，mpp_frame_has_meta(frame)并不能获得这个sei帧的user_data，这个函数的返回值不是true。我十分费解，希望获得大佬的帮助。

**Comment by HermanChen** [comment]
解码器还没有实现这个功能，sei 包在上层解析的时候可以直接读取，可以不通过解码器来获取

**Comment by xiayu0101** [comment]
在拆帧的时候解析sei确实可以，将不是sei的数据发送给解码器确实是一个有效的方法，非常感谢
