### ISSUE TITLE
MPP硬编码库缓存问题

### ISSUE THREAD

**Issue by zhangjp0405** [rockchip-linux/mpp#506]
请问MPP硬编码器里会缓存编码后的H264图像吗，如果有的话，应该如何设置不使用编码缓存，即编码完一帧后立马输出H264图像

**Comment by HermanChen** [comment]
编码器是输入图像输出码流，不会有图像输出

**Comment by zhangjp0405** [comment]
我表达错了，应该是输入图像后是否会缓存输出码流

**Comment by HermanChen** [comment]
解码有个 IMMEDIATE_OUT，可以配置成解码序输出，然后 split 也要为 0，一帧码流输入，这样输出延迟就会小些

**Comment by zhangjp0405** [comment]
好哒，感谢提示
