### ISSUE TITLE
mpp dec 输入是否支持 AVCC格式?

### ISSUE THREAD

**Issue by lion117** [rockchip-linux/mpp#511]
# 背景描述
1. RK3399
2. kylin OS aarch64

视频编码格式有两种ANNEX B和 AVCC.
使用RKMPP原生接口时, 上层业务层将整包数据下发.
1. 当数据为ANNEX B(0x00 0x00 0x00 0x01)模式时, 解码器正常解码
2. 当数据为AVCC格式时, 解码器一直无法读取到解码数据, 返回错误-11

## 问题
1. RKMPP直接支持AVCC格式解码吗? 如果支持, 应该如何设置? 
2. 参考RKMPP在ffmpeg中实现rkmppdec.c其中并未实现ANNEXB >AVCC格式的转换, 却依旧能够正常解码. 
ffmpeg的AVPACKET包都是AVCC格式.  需要自行实现ANNEXT B>AVCC格式转换吗?

**Comment by HermanChen** [comment]
1. 目前不支持
2. 转成 annexb 的比较好些
