### ISSUE TITLE
RV1126,多线程H264解码，同时多线程JPEG编码

### ISSUE THREAD

**Issue by xlwlp** [rockchip-linux/mpp#515]
使用4个线程读取RTSP视频并解码h264，同时另外4个线程对视频抽帧编码成JPG，长时间运行后板子会重启，请问1126支持这种操作方式吗？

**Comment by HermanChen** [comment]
支持的，出问题应该是哪里软件有问题

**Comment by xlwlp** [comment]
好的，我再查下代码
