### ISSUE TITLE
转换时mpp_buffer: mpp_buffer_get_ptr invalid NULL input from dump_mpp_frame_to_file

### ISSUE THREAD

**Issue by Knight1y** [rockchip-linux/mpp#522]
width = mpp_frame_get_width(frame);
    height = mpp_frame_get_height(frame);
    h_stride = mpp_frame_get_hor_stride(frame);
    v_stride = mpp_frame_get_ver_stride(frame);
    buffer = mpp_frame_get_buffer(frame);
    base = (RK_U8 *) mpp_buffer_get_ptr(buffer);

前面参数都能正常读到，到了mpp_buffer_get_ptr就开始报错mpp_buffer: mpp_buffer_get_ptr invalid NULL input from dump_mpp_frame_to_file，前面的过程是仿照mpi_dec_test的dump_mpp_frame_to_file转码写的

**Comment by stz-source** [comment]
您好，请问您解决了吗？我也遇到了类似的问题，谢谢！
