### ISSUE TITLE
H264 decoder intra-refresh

### ISSUE THREAD

**Issue by peteallenm** [rockchip-linux/mpp#523]
I am decoding a video stream that is using intra-refresh, so only has an IDR as the very first frame.
If my decoder doesn't receive this, it doesn't start decoding as it appears to wait for an IDR.
This shouldn't be necessary, as intrarefresh is refreshing the whole screen with I macroblocks every 12-16 frames.
Once the decoder has received a single IDR it decodes perfectly (and recovers well even if the stream drops out temporarily)

Is there a way to force the decoder to start decoding (or do I have to manually synthesise my own IDR of a black screen). Even if it started with a black screen it would quickly have a good image.
I am happy to provide sample files if it would be helpful.

**Comment by HermanChen** [comment]
The decoder has a control MPP_DEC_SET_DISABLE_ERROR. With this control decoder will ignore all error and send bistream to hardware.
