### ISSUE TITLE
Static build support

### ISSUE THREAD

**Issue by MarcA711** [rockchip-linux/mpp#525]
Hey,

I would like to suggest adding support for a static build, so that the user can choose at build time if he wants a static or dynamic build using a cmake flag. This way, it is easier to integrate the mpp platforms in other projects.

I saw the discussion in https://github.com/rockchip-linux/mpp/issues/459, where @HermanChen suggested to change a line in a cmake file (see https://github.com/rockchip-linux/mpp/issues/459#issuecomment-1771908914). However, this doesn't fully work, as the resulting librockchip_mpp.a will not contain all symbols because of the way, the cmake files are structured. I found a way to build a static library containing all symbols using the `ar` command. But this is a very bad way I think.

I hope you consider supporting static builds, as I think the platform will benefit from it.

**Comment by nyanmisaka** [comment]
@MarcA711 Try this commit? ec2666f

**Comment by MarcA711** [comment]
Amazing, I will try this out ASAP. Thanks for adding this feature!

**Comment by MarcA711** [comment]
When working with the new static build, I stumbled across two problems. Both are explained in my PR (https://github.com/rockchip-linux/mpp/pull/579) that tries to fix them. I reopen this issue, until my PR got merged or the problems were solved differently.

**Comment by HermanChen** [comment]
Patchs are merged. : )
