### ISSUE TITLE
rk3566 解码h264出现报错

### ISSUE THREAD

**Issue by kingofsen** [rockchip-linux/mpp#526]
1.解码H264出现无法入队的情况出现put_frame时反馈 -1024。
2.解码是在get frame是出现error 0和discard 1

**Comment by HermanChen** [comment]
1. 解码是 put_packet 和 get_frame，不会有 put_frame 的调用，是 put_packet 返回失败的话，可以等待一下再送
2. 解码时遇到错误片源是会出一 error 和 discard 标记，正常现象，可以不显示，直接 deinit 就好
