### ISSUE TITLE
RK3288下执行mpi_enc_test程序失败

### ISSUE THREAD

**Issue by zhangjp0405** [rockchip-linux/mpp#541]
在RK3288下执行"sudo ./mpi_enc_test -i video_640_480.yuv -t 7 -o encode.h264 -w 640 -h 480 -fps 25"命令失败，请问是什么原因
![微信图片_20240312193004](https://github.com/rockchip-linux/mpp/assets/48978473/dd94a0ef-8d1d-48dc-946c-8c772d75c411)
![微信图片_20240312193010](https://github.com/rockchip-linux/mpp/assets/48978473/52a6f484-f9ab-4781-a8fe-529914da345c)

**Comment by HermanChen** [comment]
内核驱动不匹配，找不到编码器，可能是 dts 没配置的问题，看下内核启动时的 log

**Comment by zhangjp0405** [comment]
> 内核驱动不匹配，找不到编码器，可能是 dts 没配置的问题，看下内核启动时的 log

如何查找H264编码器对应的设备树或修改dts设备树

**Comment by HermanChen** [comment]
提供下内核启动时候的log

**Comment by zhangjp0405** [comment]
> 提供下内核启动时候的log
 sudo cat /var/log/messages > messages.log
[messages.log](https://github.com/rockchip-linux/mpp/files/14581017/messages.log)
sudo journalctl -b  > journalctl.log
[journalctl.log](https://github.com/rockchip-linux/mpp/files/14581037/journalctl.log)
日志文件发到你邮箱了

**Comment by zhangjp0405** [comment]
是不是板子上5.16的内核版本不行，得切换到4.X系列的内核版本才行

**Comment by HermanChen** [comment]
好像没有适配过 5.16 的内核，一般用的 4.4 还是 4.19 吧？

**Comment by zhangjp0405** [comment]
想再问下，目前最新的mpp源码(比如:develop分支)能编译出.a静态库吗

**Comment by zhangjp0405** [comment]
> 好像没有适配过 5.16 的内核，一般用的 4.4 还是 4.19 吧？

![微信图片_20240313144438](https://github.com/rockchip-linux/mpp/assets/48978473/72cbfbf5-4dc6-47e1-b9c3-3c8cd61998d8)
但是官方文档上有说支持5.10，难道不支持5.16吗

**Comment by HermanChen** [comment]
只支持特定版本，不是每个版本都支持，没有人力支持太多的版本

**Comment by zhangjp0405** [comment]
想再问下，目前最新的mpp源码(比如:develop分支)能编译出.a静态库吗

**Comment by HermanChen** [comment]
目前脚本里没加静态库，我们内部加补丁试过是可以的

**Comment by zhangjp0405** [comment]
> 目前脚本里没加静态库，我们内部加补丁试过是可以的

在MPP源码里怎么加补丁可以编译出能用的静态库？
