### ISSUE TITLE
你好，使用rk3588 的 mpi_enc_test  CQP码控发现h.265 比h.264的bdrate 更差？是什么原因造成的？

### ISSUE THREAD

**Issue by REO-RAO** [rockchip-linux/mpp#543]
命令行如下;

./mpi_enc_test -w 1280 -h 720 -t 7 -rc 2 -fqc 28:28:32:32 -fps 30 -f 4  -i jctvc_b_Kimono_1280x720_30.yuv -o jctvc_b_Kimono_1280x720_30-cqp32-qpip4.h264

./mpi_enc_test -w 1280 -h 720 -t 16777220 -rc 2 -fqc 28:28:32:32 -fps 30 -f 4  -i jctvc_b_Kimono_1280x720_30.yuv -o jctvc_b_Kimono_1280x720_30-cqp32-qpip4.h265

ps: 我的265 的命令行有问题吗？

**Comment by HermanChen** [comment]
代码更新了，麻烦再测试一下

**Comment by REO-RAO** [comment]
你好，我更新之后，编码出的265 码流还是色块，是我上面的编码命令不对吗？

![image](https://github.com/rockchip-linux/mpp/assets/19755367/d1662b58-962e-4dd8-8fb0-a9f9ece0d124)

**Comment by HermanChen** [comment]
-i 的文件路径是不是有问题？
