### ISSUE TITLE
librockchip_mpp.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zhangjp0405** [rockchip-linux/mpp#547]
当启动可执行程序时，报找不到librockchip_mpp.so.1库，但是已经使用"export LD_LIBRARY_PATH"命令并且用ldd可以看到已经有librockchip_mpp.so.1库，这是为什么
![QQ截图20240313194053](https://github.com/rockchip-linux/mpp/assets/48978473/ee64b063-7602-41c7-a745-130bace3b0f2)

**Comment by HermanChen** [comment]
librockchip_mpp.so.1 应该是个符号链连吧？正常是链到  librockchip_mpp.so.0 这个实体
