### ISSUE TITLE
你好，在rk3588 上配置全图的ROI，发现不生效，其结果期望的ROI QP结果差很多是什么原因？ 配置全图ROI的图像QP分布如下，谢谢

### ISSUE THREAD

**Issue by REO-RAO** [rockchip-linux/mpp#550]
第一帧是期望的结果：

第一帧块级QP截图;

![image](https://github.com/rockchip-linux/mpp/assets/19755367/3be5db42-7125-4ce1-83b9-2eb130be61bd)

第二帧块级QP截图：第二帧不是期望的结果是什么原因：
![image](https://github.com/rockchip-linux/mpp/assets/19755367/4c1a03a7-a178-46bd-b8f6-4ab74f877fe1)

**Comment by LiaoYujia** [comment]
请问这个块级QP截图 是通过什么软件得到的呢？
