### ISSUE TITLE
问题: 在RK3588上如何知道MPP的使用百分比？

### ISSUE THREAD

**Issue by bluesky2319** [rockchip-linux/mpp#555]
有没有一条命令可以监视 MPP 编码器和解码器的使用百分比？例如，在 Nvidia GPU 中，我们可以使用 "nvidia-smi dmon" 命令监视使用百分比。那么 MPP 怎么样，我们如何检查使用百分比？

**Comment by HermanChen** [comment]
目前还没有办法

**Comment by bluesky2319** [comment]
好的，谢谢您的回复。
