### ISSUE TITLE
你好，使用rk3588的mpi_enc_test 编码出来的h264码流，发现chroma_qp_index_offset设置为-6，导致主观问题，请问能否开放chroma_qp_index_offset参数设置或者修复这个问题（至少改成chroma_qp_index_offset=0）

### ISSUE THREAD

**Issue by REO-RAO** [rockchip-linux/mpp#559]
如上：
![image](https://github.com/rockchip-linux/mpp/assets/19755367/0a1446dc-f4c1-41a5-a398-da2c564039cf)

**Comment by HermanChen** [comment]
可以配置h264:cb_qp_offset和h264:cr_qp_offset，或者h265:cb_qp_offset和h265:cr_qp_offset
