### ISSUE TITLE
VP8 hardware encoder support

### ISSUE THREAD

**Issue by gonzoua** [rockchip-linux/mpp#56]
RK3399 spec states that it supports hardware VP8 encoding but I didn't find relevant code in MPP release branch. Is there any plans to add it and if yes when can it be expected? If there are no plans - what another stack can be used for VP8 encoding on RK3399?

Thank you

**Comment by WainDing** [comment]
Vp8 hardware encoding is planned, which debuging in progress,  and will be launched in a month.It will support RK3399. Thank you for your thoughtfulness.

**Comment by gonzoua** [comment]
Great! Thanks for the update.
