### ISSUE TITLE
h264编码设置限制NAL的最大大小无效

### ISSUE THREAD

**Issue by xb985547608** [rockchip-linux/mpp#562]
我需要控制每个nal的大小在1500以下，在256bps的码率下，nal的大小可以保证都在1500以下，但是我将码率调整到512bps后，部分nal大小将超过了1500，请问我该如何做才能保证在任何码率下都可以确保nal的大小不超过1500

mpp_enc_cfg_set_u32(d->cfg, "split:mode", MPP_ENC_SPLIT_BY_BYTE);
mpp_enc_cfg_set_u32(d->cfg, "split:arg", 1480);

硬件平台：rk3128
编码大小：640*480
mpp_info: mpp version: 0b5a25d9 author: Herman Chen   2020-07-24 [utils]: Fix encoder width / stride mismatch

**Comment by HermanChen** [comment]
把 split:arg 配置得更小一些，因为编码一个块的长度变化是比较大的，不一定能 100% 限制住，需要留点余量
