### ISSUE TITLE
It is required to bump the version

### ISSUE THREAD

**Issue by xaionaro** [rockchip-linux/mpp#566]
It looks like file https://github.com/rockchip-linux/mpp/blob/ee946af015c350c926a0fca2f02da8e429f8b079/pkgconfig/rockchip_mpp.pc.cmake#L9 last time was updated 4 years ago. Meanwhile it seems like a lot of things changed in the library. For example, apparently usage of the old version of the lib causes this variant of ffmpeg to segfault: https://github.com/nyanmisaka/ffmpeg-rockchip/issues/56#issue-2224137907

So to avoid these segfaults one would need to check if the library is fresh enough, which requires the version of the lib itself be periodically bumped.

Also it looks like the latest release was long time ago, which might make various distributions to use severely outdated version of the lib.

**Comment by great9** [comment]
agreed. it can solve that segfault.
ping @HermanChen

**Comment by HermanChen** [comment]
Use new version tag 1.0.x or update a larger number than 1.3.8?

**Comment by great9** [comment]
> Use new version tag 1.0.x or update a larger number than 1.3.8?

update to a larger number that makes sense with the rest of the mpp

**Comment by HermanChen** [comment]
1.0.5 tag has update the number to 1.3.9

**Comment by xaionaro** [comment]
Thanks!

**Comment by xaionaro** [comment]
P.S.: Does it makes sense to make an official release so that distribution maintainers will see they need to update the version of the package? https://github.com/rockchip-linux/mpp/releases

**Comment by HermanChen** [comment]
> P.S.: Does it makes sense to make an official release so that distribution maintainers will see they need to update the version of the package? https://github.com/rockchip-linux/mpp/releases

Done

**Comment by xaionaro** [comment]
Thanks!
