### ISSUE TITLE
mpp支持通过SEI添加一些备注信息吗

### ISSUE THREAD

**Issue by Newcomer-CL** [rockchip-linux/mpp#572]
想通过mpp编码的时候添加一些描述性的信息，mpp是否支持？
查看了mpp的文档，有一些说明，但不详细
![image](https://github.com/rockchip-linux/mpp/assets/66213037/11e77287-d68d-4e86-8db4-64fdc3c5c5d4)
![image](https://github.com/rockchip-linux/mpp/assets/66213037/475f331f-aec2-4e1e-9361-c088a3493fa0)

**Comment by HermanChen** [comment]
在每帧的 meta 里加上 USER_DATA2 的信息即可

**Comment by Newcomer-CL** [comment]
有相关的示例代码、demo、文档吗

**Comment by HermanChen** [comment]
看 mpi_enc_test

**Comment by Newcomer-CL** [comment]
![image](https://github.com/rockchip-linux/mpp/assets/66213037/0131fd37-ad6b-4a84-ab57-9f7f8f254cc9)
是这一块吗

**Comment by HermanChen** [comment]
是的

**Comment by Newcomer-CL** [comment]
好的，感谢。确实是可以的，我把demo生成的h264文件输出出来，能看到SEI信息
![image](https://github.com/rockchip-linux/mpp/assets/66213037/cb59e92a-6f7f-4b58-b7a2-745fe8ac9794)

**Comment by Newcomer-CL** [comment]
还有个疑问就是这个SEI的长度感觉对不上啊，我不理解为什么06 05 后面一个是38 一个是53，按道理不是放入的字符串所占的字节总数+结束符80

**Comment by HermanChen** [comment]
看协议里对sei_message的描述

**Comment by Newcomer-CL** [comment]
MPP编码h264的协议在哪个文档中描述的？开发文档里面没找到

**Comment by HermanChen** [comment]
是 H.264 协议文档，不是 MPP 的开发文档

**Comment by Newcomer-CL** [comment]
好的，感谢
