### ISSUE TITLE
mpp_init失败返回mpp_nok

### ISSUE THREAD

**Issue by chenhandsomechen** [rockchip-linux/mpp#574]
同样的代码和库在rk上可以正常运行，但是在unbuntu上，mpp_init，参数是解码h265 函数返回-1，也就是mpp_nok，请问是什么原因，使用的也是最新的代码

**Comment by HermanChen** [comment]
需要依赖内核驱动的支持

**Comment by chenhandsomechen** [comment]
是在x86的机器上不可以使用吗，还是需要安装什么驱动

**Comment by HermanChen** [comment]
RK 的驱动只能在 RK 的芯片上用啊……x86 的机器上哪里来 RK soc 上的硬件编解码器
