### ISSUE TITLE
关于h264编码的问题

### ISSUE THREAD

**Issue by Kevin111369** [rockchip-linux/mpp#575]
我参考mpi_enc_test实现了h264编码，使用mpp_packet_get_pos和mpp_packet_get_length可以获得packet的data和size，但是mpp_packet_get_pts和mpp_packet_get_dts获得的pts和dts一直为0，请问这是什么原因呢？

**Comment by HermanChen** [comment]
输出的 pts 和 dts 取决于输入 frame 的 pts 和 dts，mpp 编码只是透传这些数据
