### ISSUE TITLE
3588转码失败

### ISSUE THREAD

**Issue by zhang-chuanfeng** [rockchip-linux/mpp#581]
![image](https://github.com/rockchip-linux/mpp/assets/59160162/48ac1a12-79d8-4457-b55a-e045d3e4d5d9)
同一份代码在3568可以使用  在3588上转码失败。
看到这里有mpp_buffer的报错  是不是与系统环境有关。代码申请buffer都是通过DRM来申请的。

是不是DRM申请失败导致的？

**Comment by zhang-chuanfeng** [comment]
这是3568上的日志
![Uploading image.png…]()

**Comment by zhang-chuanfeng** [comment]
![image](https://github.com/rockchip-linux/mpp/assets/59160162/8b0aa409-c53d-4af9-acc7-806752e592b8)

这是3568的日志

**Comment by zhang-chuanfeng** [comment]
错误应该是这里  报解析265帧NAL失败
![image](https://github.com/rockchip-linux/mpp/assets/59160162/a0dc7751-c0ca-4a72-ac3b-b620affb04a0)

**Comment by HermanChen** [comment]
> ![image](https://private-user-images.githubusercontent.com/59160162/325495219-48ac1a12-79d8-4457-b55a-e045d3e4d5d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzEwNzAsIm5iZiI6MTcxNDAzMDc3MCwicGF0aCI6Ii81OTE2MDE2Mi8zMjU0OTUyMTktNDhhYzFhMTItNzlkOC00NDU3LWI1NWEtZTA0NWQzZTRkNWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA3MzkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYTQ1YzQzNTdiMzk2MDBlMjk0NWNiMDBlNmY3NGMxNzI1MWQ1Y2NlOTYzOTFkZTI4OGQ1OWE4MzczMjAwMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-m7CmcKAdvk2Dzu7jdE8yVeYpLPWG_Erbv6LGzB5ovo) 同一份代码在3568可以使用 在3588上转码失败。 看到这里有mpp_buffer的报错 是不是与系统环境有关。代码申请buffer都是通过DRM来申请的。
> 
> 是不是DRM申请失败导致的？

这个是编码器配置出错

**Comment by zhang-chuanfeng** [comment]
> > ![image](https://private-user-images.githubusercontent.com/59160162/325495219-48ac1a12-79d8-4457-b55a-e045d3e4d5d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzEwNzAsIm5iZiI6MTcxNDAzMDc3MCwicGF0aCI6Ii81OTE2MDE2Mi8zMjU0OTUyMTktNDhhYzFhMTItNzlkOC00NDU3LWI1NWEtZTA0NWQzZTRkNWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA3MzkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYTQ1YzQzNTdiMzk2MDBlMjk0NWNiMDBlNmY3NGMxNzI1MWQ1Y2NlOTYzOTFkZTI4OGQ1OWE4MzczMjAwMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-m7CmcKAdvk2Dzu7jdE8yVeYpLPWG_Erbv6LGzB5ovo) 同一份代码在3568可以使用 在3588上转码失败。 看到这里有mpp_buffer的报错 是不是与系统环境有关。代码申请buffer都是通过DRM来申请的。
> > 是不是DRM申请失败导致的？
> 
> 这个是编码器配置出错
调整了编码器配置好像还不行  能帮看出什么问题吗？
![image](https://github.com/rockchip-linux/mpp/assets/59160162/6d834311-e178-49d0-b9db-f8d62ad99469)

**Comment by zhang-chuanfeng** [comment]
> > ![image](https://private-user-images.githubusercontent.com/59160162/325495219-48ac1a12-79d8-4457-b55a-e045d3e4d5d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzEwNzAsIm5iZiI6MTcxNDAzMDc3MCwicGF0aCI6Ii81OTE2MDE2Mi8zMjU0OTUyMTktNDhhYzFhMTItNzlkOC00NDU3LWI1NWEtZTA0NWQzZTRkNWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA3MzkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYTQ1YzQzNTdiMzk2MDBlMjk0NWNiMDBlNmY3NGMxNzI1MWQ1Y2NlOTYzOTFkZTI4OGQ1OWE4MzczMjAwMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-m7CmcKAdvk2Dzu7jdE8yVeYpLPWG_Erbv6LGzB5ovo) 同一份代码在3568可以使用 在3588上转码失败。 看到这里有mpp_buffer的报错 是不是与系统环境有关。代码申请buffer都是通过DRM来申请的。
> > 是不是DRM申请失败导致的？
> 
> 这个是编码器配置出错

调整了编码器配置后 3588编出来一帧  去除sement长度后可以  但是3568转出r后花屏

3568如果通过这种方式获取seg_length不会花屏，但是3588会花屏
![image](https://github.com/rockchip-linux/mpp/assets/59160162/7c7e4ab8-705c-4742-a6bf-96e08ec4265d)


3588如果通过下图方式获取seg_length不会花屏，但是3568会花屏
![image](https://github.com/rockchip-linux/mpp/assets/59160162/61c78a90-1eb0-47e0-8c50-d6a3a1db2baf)

**Comment by zhang-chuanfeng** [comment]
知道原因了  是seg段有差异
3588的seg
![image](https://github.com/rockchip-linux/mpp/assets/59160162/75ba326f-7dc6-4a93-ba37-93be03d3ff8b)

3568的seg划分
![image](https://github.com/rockchip-linux/mpp/assets/59160162/850b9776-e9bd-41b0-b37b-804411de0601)
