### ISSUE TITLE
请问MPP_VIDEO_CodingMJPEG编码支持OSD功能吗

### ISSUE THREAD

**Issue by denghengli** [rockchip-linux/mpp#590]
问题：mpp的MPP_VIDEO_CodingMJPEG编码支持OSD字符叠加功能吗
现象：1、使用官方的test程序
export osd_enable=1
mpi_enc_test -i yuv420p_1280x720.yuv -w 1280 -h 720 -f 4 -t 7 -o yuv420p_1280x720.h264  编码后的视频有色块，OSD叠加成功了
mpi_enc_test -i yuv420p_1280x720.yuv -w 1280 -h 720 -f 4 -t 8 -o jpegout.jpg 编码后的图片没有色块，OSD叠加的色块在MPP_VIDEO_CodingMJPEG编码时不生效？
2、通过mpp api开发的程序，现象跟用官方的test程序一样，MPP_VIDEO_CodingHEVC编码的时候可以OSD叠加，MPP_VIDEO_CodingMJPEG编码的时候OSD叠加不生效

**Comment by HermanChen** [comment]
jpeg 编码不支持 osd 功能

**Comment by Sacmer** [comment]
> jpeg 编码不支持 osd 功能

如果我编码成h264时想要添加自定义的osd水印 需要怎么做 需要用RGA吗

**Comment by denghengli** [comment]
> > jpeg 编码不支持 osd 功能
> 
> 如果我编码成h264时想要添加自定义的osd水印 需要怎么做 需要用RGA吗

用mpp的OSD就可以哈
