### ISSUE TITLE
当使用mpp解码mjpeg视频时，第一帧就会出现MPP_ERR_BUFFER_FULL

### ISSUE THREAD

**Issue by Washington-DC** [rockchip-linux/mpp#594]
![image](https://github.com/rockchip-linux/mpp/assets/12068390/4e4d7489-f294-4d0a-a23a-e8fc73a912fe)

![image](https://github.com/rockchip-linux/mpp/assets/12068390/b28895ff-7e39-412d-8049-c87ee3c1959c)

如图，当使用mpp解码mjpeg视频时，第一帧就会出现MPP_ERR_BUFFER_FULL，但是如果解码的是h264视频就是正常的

**Comment by HermanChen** [comment]
用 mpi_dec_test 跑一下试试，jpeg 解码需要用 advanced 流程里的处理来解码

**Comment by TRYOKETHEPEN** [comment]
请参考：
https://github.com/rockchip-linux/mpp/issues/592#issuecomment-2101716446

**Comment by Washington-DC** [comment]
i got it, thanks
