### ISSUE TITLE
mpp多路视频并行解码崩溃

### ISSUE THREAD

**Issue by 1204465458** [rockchip-linux/mpp#595]
瑞芯微的小伙伴  希望提供一些建议  谢谢

并行13路 1080p 25fps  视频解码  mpp库出现崩溃   低于13路时  视频解码正常

系统：Debian GNU/Linux 11 (bullseye)   
cpu： arm64    
mpp版本(tag)： 1.0.5   

堆栈信息如下
![Screenshot from 2024-05-08 15-19-29](https://github.com/rockchip-linux/mpp/assets/53364162/cf7161f3-b4d8-4eb8-bee6-ebc369e4bfd8)

**Comment by qvoid** [comment]
芯片RK3566？13路都是解码同一个视频吗？

**Comment by 1204465458** [comment]
RK3588平台  13路都解码同一个视频

**Comment by qvoid** [comment]
可以用 `build/linux/arm/test/mpi_dec_multi_test` 测试看看是否能够复现。
测试命令：
```
mpi_dec_multi_test -i xxx.h264 -s 13
```
> 如果是 64位的板子，推 aarch64目录下的
> 码流需要先去封装，抽出 annexb的 H.264 bitstream，可以用ffmpeg做。

**Comment by 1204465458** [comment]
感谢，经排查是厂商板子适配有问题，原有服务通过docker方式运行，并行13路正常，不再出现上述问题
