### ISSUE TITLE
performance: explicit sleep in Mpp::get_frame

### ISSUE THREAD

**Issue by mcerveny** [rockchip-linux/mpp#6]
Hello. 

There is explicit msleep() in https://github.com/rockchip-linux/mpp/blob/develop/mpp/mpp.cpp#L289
Can it be removed or moved to non MPP_POLL_BLOCK (cv wait) branch ?

Thanks, M.C>

**Comment by HermanChen** [comment]
I am not familiar with gitHub. How to merge this commit? : )

**Comment by HermanChen** [comment]
Find a way to do it : )
