### ISSUE TITLE
RK3566 使用MPP解码MJPEG，输出格式设置为MPP_FMT_BGRA8888，输出不正常

### ISSUE THREAD

**Issue by SeewayU** [rockchip-linux/mpp#600]
![1715938605948](https://github.com/rockchip-linux/mpp/assets/13775477/6c8e2653-b77c-4bdc-b6e4-d1da84ff3235)
你好！
RK3566 使用MPP解码MJPEG，输出格式设置为MPP_FMT_BGRA8888，输出不正常，如图片所示，
但是同样的代码将输出格式改为MPP_FMT_YUV420SP，就没有问题，请问这是什么原因造成的？
系统为Ubuntu 22.04.4 LTS (GNU/Linux 4.19.232 aarch64)

**Comment by HermanChen** [comment]
3566 的 jpeg 解码器不带格式转换，只能输出 YUV420，无法转成 8888

**Comment by SeewayU** [comment]
> 3566 的 jpeg 解码器不带格式转换，只能输出 YUV420，无法转成 8888

那是不是只能用rga将YUV420转成8888了，顺便问一下哪颗芯片的jpeg解码器带格式转换？ 3588有吗？

**Comment by HermanChen** [comment]
后面都不带了，因为格式转换模块的面积比 jpeg 解码本体还大，格式转换放到 rga 里做

**Comment by SeewayU** [comment]
好的 感谢回复



---- 回复的原邮件 ----
| 发件人 | Herman ***@***.***> |
| 日期 | 2024年05月17日 19:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [rockchip-linux/mpp] RK3566 使用MPP解码MJPEG，输出格式设置为MPP_FMT_BGRA8888，输出不正常 (Issue #600) |

后面都不带了，因为格式转换模块的面积比 jpeg 解码本体还大，格式转换放到 rga 里做
