### ISSUE TITLE
H265 rtsp拉流报了这个错误 "Bitstream is encoded by special encoder"

### ISSUE THREAD

**Issue by junpinglv** [rockchip-linux/mpp#603]
H265 rtsp拉流报了这个错误 "Bitstream is encoded by special encoder"，有没有办法解决？

**Comment by junpinglv** [comment]
H265  rtsp拉流报了这个错误 "Bitstream is encoded by special encoder"，有没有办法解决？

**Comment by qvoid** [comment]
拉取的视频流是使用DivX encoder编码的。如果想要解码，需要设备和解码器获得相应的授权和认证才可以解码。
