### ISSUE TITLE
在rk3588上使用 mpi_rc2_test 进行h265编码报错

### ISSUE THREAD

**Issue by chenjh1225** [rockchip-linux/mpp#604]
mpp版本：1.0.5
命令： ./mpi_rc2_test -i src.mp4 -o dst.h265 -w 1280 -h 720 -fps 25 -t 16777220

May 22 12:36:05 debian mpp[2392575]: mpi_enc_utils: cmd parse result:
May 22 12:36:05 debian mpp[2392575]: mpi_enc_utils: input  file name: src.mp4
May 22 12:36:05 debian mpp[2392575]: mpi_enc_utils: output file name: dst.h265
May 22 12:36:05 debian mpp[2392575]: mpi_enc_utils: width      : 1280
May 22 12:36:05 debian mpp[2392575]: mpi_enc_utils: height     : 720
May 22 12:36:05 debian mpp[2392575]: mpi_enc_utils: format     : 0
May 22 12:36:05 debian mpp[2392575]: mpi_enc_utils: type       : 16777220
May 22 12:36:05 debian mpp[2392575]: mpi_rc_test: input file src.mp4 size 1496546
May 22 12:36:05 debian mpp[2392575]: mpp_dma_heap: os_allocator_dma_heap_open open dma heap type 0 system-uncached failed!
May 22 12:36:05 debian mpp[2392575]: mpp_buffer: MppBufferService get_group failed to get allocater with mode 0 type 1
May 22 12:36:05 debian mpp[2392575]: mpi_rc_test: failed to get buffer group for output packet ret -1
May 22 12:36:05 debian mpp[2392575]: mpi_rc_test: mpi_rc_codec 1887472576 failed

**Comment by HermanChen** [comment]
mpp_dma_heap: os_allocator_dma_heap_open open dma heap type 0 system-uncached failed!
内核的 dmaheap 没开，另外，编码器只接受图像输入，不接受 mp4 文件输入，要从 mp4 文件中提取 265 文件用 ffmpeg
