### ISSUE TITLE
在rk3588上是否可以动态设置编码码率？

### ISSUE THREAD

**Issue by jih488** [rockchip-linux/mpp#605]
我在rk3588上使用mpi接口进行编码，是否可以使用RK_MPI_VENC_SetChnAttr或其他接口来动态设置编码码率？调整之前是否需要unbind相关的设备？

**Comment by HermanChen** [comment]
mpi 接口的使用参考 mpi_enc_test，RK_MPI_VENC_SetChnAttr 这个是 rockit 的接口，不是 mpp 的

**Comment by jih488** [comment]
> mpi 接口的使用参考 mpi_enc_test，RK_MPI_VENC_SetChnAttr 这个是 rockit 的接口，不是 mpp 的

哦哦，那rockit有可以动态设置编码帧率的接口吗？我用RK_MPI_VENC_SetChnAttr设置进去，再用RK_MPI_VENC_GetChnAttr读出来，stAttr.stRcAttr.stH264Cbr.u32BitRate 这个值确实发生变化了，但是编码出的文件大小没有变化。

**Comment by HermanChen** [comment]
rockit 这个不太清楚，应该也是可以动态配置的

**Comment by GavinLook** [comment]
Android上直接动态设置framerate是有效的
setupFrameRate
MPP_ENC_SET_RC_CFG

**Comment by HermanChen** [comment]
ok，如果问题解决请关闭问题

**Comment by jih488** [comment]
rockit 可以用 RK_MPI_VENC_SetChnAttr 接口在运行时设置码率。
