### ISSUE TITLE
RK3588 在使用rockit接口设置vo时，UI消失

### ISSUE THREAD

**Issue by jih488** [rockchip-linux/mpp#611]
使用RK3588，先通过vo显示出来了UI，然后希望通过vo输出解码的视频，在设置vo时，在调用RK_MPI_VO_GetPubAttr接口，UI直接消失，所在进程依然运行。RK_MPI_VO_GetPubAttr这个接口返回值为0. 具体日志如图：
![无标题1](https://github.com/rockchip-linux/mpp/assets/7875984/664cf0a0-57e7-47f9-9e3d-5619666b0cd1)

代码为demo代码 test_mpi_vdec.cpp

![无标题2](https://github.com/rockchip-linux/mpp/assets/7875984/b47c4e12-59d3-4c95-8b91-3338c8e7910d)

继续执行解码输出，视频可以显示。

**Comment by HermanChen** [comment]
这个是 rockit 的问题吧，不在 mpp 里处理的……

**Comment by jih488** [comment]
> 这个是 rockit 的问题吧，不在 mpp 里处理的……

没找到你们的rockit问题该在哪提问啊？

**Comment by HermanChen** [comment]
到公司的官方 redmine 上提 rockit 的问题

**Comment by jih488** [comment]
> 到公司的官方 redmine 上提 rockit 的问题

在你们的redmine注册完，管理员审核了快一个月了。。。。。。

**Comment by HermanChen** [comment]
你们公司要是有和 RK FAE 的联系人的话，通过他们去联系下
