### ISSUE TITLE
只有p帧的h265视频无法解码

### ISSUE THREAD

**Issue by xiayu0101** [rockchip-linux/mpp#619]
我这有一段h265视频，它只有p帧，没有i帧，使用windows的cuda硬解码和libx265软解码可以得到正常的yuv图像，但是使用rk3588的硬件解码没有输出，之前也试过一些其他平台的硬解码器，也有类似的问题，请教大佬们如何使用rk3588的硬件解码器解码这种只有p帧的数据。

**Comment by HermanChen** [comment]
有个 mpp_dec_cfg 里有个 disable_error 的配置，关报错，让硬件强行解码
