### ISSUE TITLE
YUV420SP编码成MJPEG视频，只有一帧

### ISSUE THREAD

**Issue by ZiYuan2023** [rockchip-linux/mpp#620]
mpi_enc_test编码YUV420SP，输出MJPEG视频。输入的YUV源视频有19秒，输出的视频只有一帧循环10秒

**Comment by ZiYuan2023** [comment]
![屏幕截图 2024-06-21 145406](https://github.com/rockchip-linux/mpp/assets/151907625/1a3a5601-f280-46f9-a2bb-e161827b5bad)
麻烦大佬们解答一下是为什么，命令：
sudo ./mpi_enc_test -i /Debian/T1080_2.yuv -o /Debian/H1080.mjpeg -t 8 -w 1920 -h 1080 -fps 25

**Comment by HermanChen** [comment]
test 的 jpeg 编码写得有点问题，逻辑上应该只编码 1 帧……

**Comment by ZiYuan2023** [comment]
> test 的 jpeg 编码写得有点问题，逻辑上应该只编码 1 帧......

好的明白了，谢谢大佬！
