### ISSUE TITLE
the plan for implementation ISP APIs of MPI

### ISSUE THREAD

**Issue by plumnew** [rockchip-linux/mpp#627]
I would like to konw when this parts implememted.
now i am seeking a solution to feed the isp processer raw images directly then get the results images back and during the same time, we could set the isp parameters.
from the wiki description https://opensource.rock-chips.com/wiki_Rockchip-isp1, it seems not possible change the pipeline to get the image from memory directly.
![image](https://github.com/rockchip-linux/mpp/assets/26968391/50e1c477-2a1d-4bcc-b55f-10686975625b)
many thanks~

**Comment by HermanChen** [comment]
ISP is not in mpp libary.

**Comment by plumnew** [comment]
https://github.com/rockchip-linux/mpp/blob/develop/mpp/mpi.cpp
static MPP_RET mpi_isp(MppCtx ctx, MppFrame dst, MppFrame src);
static MPP_RET mpi_isp_put_frame(MppCtx ctx, MppFrame frame);
static MPP_RET mpi_isp_get_frame(MppCtx ctx, MppFrame *frame);

in this file, there are three reserved APIs for ISP functions. Are that deprecated? if it would not support in mpp, where could i directly access these APIs?  Are there suggestions for this use case? thanks~

**Comment by HermanChen** [comment]
These api is not implemented and reserved for future video pre/post-process.

**Comment by plumnew** [comment]
> These api is not implemented and reserved for future video pre/post-process.

thanks, and we could close this ticket.
