### ISSUE TITLE
mpp integration in yocto for sofia-3gr

### ISSUE THREAD

**Issue by bmoraine** [rockchip-linux/mpp#63]
I am interested to add mpp to yocto for a sofia-3gr target.

A mpp recipe for yocto is already exisiting here:
https://git.phytec.de/meta-phytec/tree/recipes-multimedia/rockchip-mpp

This recipe that targets rk3288 seems to use very few  CMAKE options (RKPLATFORM=ON & HAVE_DRM=ON)

I would like to  know  if these options are still valid for a sofia-3gr target or some other options must be used

According these files 
https://github.com/rockchip-linux/mpp/blob/release/build/linux/x86/sofia-3gr
RKPLATFORM must be ON and SOFIA_3GR_LINUX must be set

Could you confirm?

Regards

**Comment by HermanChen** [comment]
SOFIA_3GR_LINUX macro can be off now.
For old 3gr platform only support 3.10 kernel which has ion allocator only. Then comes these macro.
When port to kernel with drm SOFIA_3GR_LINUX macro can be deleted.
RKPLATFORM and HAVE_DRM are better to be always on.
Thanks for using MPP : )

**Comment by bmoraine** [comment]
Thank you for these clarifications.

So I can use without modification Roxkchip mpp recipe
https://github.com/rockchip-linux/meta-rockchip/tree/master/recipes-multimedia/rockchip-mpp
at the exeption of libvu dependencies.

Indeed could you please precise where to find rockchip-vpu recipe 
`bmoraine@bmoraine-SVS13A1C5E:/opt$ grep -r vpu meta-rockchip/
meta-rockchip/recipes-multimedia/gstreamer-rockchip/gstreamer1.0-rockchip.inc:PACKAGECONFIG[vpudec] = "--enable-vpudec,--disable-vpudec,rockchip-vpu"
meta-rockchip/recipes-multimedia/rockchip-mpp/rockchip-mpp.inc:PACKAGES = "${PN}-demos ${PN}-dbg ${PN}-staticdev ${PN}-dev ${PN} rockchip-vpu"
meta-rockchip/recipes-multimedia/rockchip-mpp/rockchip-mpp.inc:FILES_rockchip-vpu = "${libdir}/lib*vpu${SOLIBS}"
meta-rockchip/recipes-core/udev/udev-extraconf/10-rk.rules:KERNEL=="vpu-service", MODE="0666", GROUP="video"
meta-rockchip/recipes-core/udev/udev-extraconf/10-rk.rules:KERNEL=="vpu_service", MODE="0666", GROUP="video"
bmoraine@bmoraine-SVS13A1C5E:/opt$ find meta-rockchip -name "*vpu*"
bmoraine@bmoraine-SVS13A1C5E:/opt$`

In one of my yocto layer provided by Intel, I have a recipe providing libvpu.so.2.0.0. I assume it is equivalent. Could you confirm?

Regards
