### ISSUE TITLE
3588 编码1080 40Mbps 的mjpeg 系统崩溃

### ISSUE THREAD

**Issue by yukuilong** [rockchip-linux/mpp#639]
Android13 
编码mjpeg 640*360 ，mjpeg 1280*720 都是正常的 ，但是编码1080分辨率时 系统就崩溃了，报错信息如下：
![11](https://github.com/user-attachments/assets/5ff6538c-282f-458b-90ee-d6ed4f9683e0)

**Comment by HermanChen** [comment]
输入图像 stride 需要 16 对齐

**Comment by yukuilong** [comment]
输入的分辨率是 1920*1080  的 ，wstride 是16 对齐的 ，hstride 也要16对齐吗

**Comment by HermanChen** [comment]
是的，这版的老 jpeg 编码器需要水平垂直都 16 对齐，比较麻烦

**Comment by yukuilong** [comment]
嗯 改成 16对齐可以了 ，感谢
