### ISSUE TITLE
RK3588 JPEG解码输出帧格式问题

### ISSUE THREAD

**Issue by ZiYuan2023** [rockchip-linux/mpp#649]
命令 
sudo ./mpi_dec_test -i /Debian/RGB/40.bin -o /Debian/10.bin -w 1920 -h 1080 -t 8 -f 65549

输出
![屏幕截图 2024-08-13 084144](https://github.com/user-attachments/assets/3984f229-132b-44ad-9f82-df72fc071146)

请问目前JPEG解码不支持RGBA8888的格式吗

**Comment by HermanChen** [comment]
3588 的 jpeg 解码器没有输出格式转换功能，需要用 rga 来做格式转换
