### ISSUE TITLE
如何获取mpp的版本号

### ISSUE THREAD

**Issue by lxzlife** [rockchip-linux/mpp#661]
mpp_api->version为0，如何获取一个mpp库的版本号？

**Comment by lxzlife** [comment]
已知pkgconfig里的版本是1.3.8，对应的源码发行版本是？

**Comment by HermanChen** [comment]
看编译生成的 version.h，主要是用 git 里的版本号，目前mpp_api->version这个变量没启用……

**Comment by lxzlife** [comment]
@HermanChen 板子里自带的，不知道，看着像release2017的那版，没有mpp_vdec_cfg_init函数

**Comment by HermanChen** [comment]
那估计还是比较旧 strings libmpp.so | grep author 看看版本信息

**Comment by HermanChen** [comment]
那估计还是比较旧 strings libmpp.so | grep author 看看版本信息

**Comment by lxzlife** [comment]
没有信息返回

**Comment by lxzlife** [comment]
@HermanChen 还有就是h264解码调用一定次数decode_put_packet后返回MPP_ERR_BUFFER_FULL 
代码流程是这样的
![mpp](https://github.com/user-attachments/assets/7c446eb6-f2e1-4948-93b7-58a5d3bad5ef)

**Comment by lxzlife** [comment]
@HermanChen soc是rk3399pro

**Comment by HermanChen** [comment]
跑 mpi_dec_test 看看

**Comment by lxzlife** [comment]
@HermanChen 版本问题找到和环境编译厂家，说是1.0.0(2020年编译的)，但是这时候github还没发行1.0.0版本；decode_put_packet返回缓冲满问题找到了

**Comment by HermanChen** [comment]
好的，感谢说明~
