### ISSUE TITLE
rk3399解码h264会有一帧延迟吗？

### ISSUE THREAD

**Issue by wer881027** [rockchip-linux/mpp#665]
我基于FFmpegg5.1.3代码修改可以调用mpp解码h264了，不过放入第2帧时第1帧图像数据才出来，会有一帧延迟。 我确定是读一帧rkmpp_write_data一帧，第一帧包含sps pps Iframe，视频源没有B帧在其它解码器上是没有延迟的，同时设置了MPP_DEC_SET_IMMEDIATE_OUT。rk3399解码h264会有一帧延迟吗？

希望官方能提供 MPP_DEC_SET_PARSER_SPLIT_MODE=0 的例子，  最好还能有zero copy渲染显示的例子(我使用sdlrender渲染很慢)

**Comment by HermanChen** [comment]
用 IMMEDIATE_OUT 选项加 SPLIT_MODE 0

**Comment by HermanChen** [comment]
零拷贝的话，buffer 提交需要使用外部 buffer 模式比较好

**Comment by wer881027** [comment]
> 用 IMMEDIATE_OUT 选项加 SPLIT_MODE 0

感谢回答。是我代码的问题，设置IMMEDIATE_OUT和SPLIT_MODE 0后，第一次仍I帧进去，需调用2次decode_get_frame， 第一次返回mpp_frame_get_info_change， 第二次能返回图像数据， 不会有延迟的。
