### ISSUE TITLE
mpp解码mjpeg，视频分辨率太高（3840*1080）的时候出现解码不正常现象。 

### ISSUE THREAD

**Issue by Lizi633** [rockchip-linux/mpp#667]
用mpp解码3200 * 1200的mjpeg视频流是正常的，但是解码3840 * 1080的视频流就出现了异常。得到的解码图片是这样的
![video0](https://github.com/user-attachments/assets/6261aff2-b4d3-4786-bf59-edf166226dd1)
第一行会有花屏现象。其他分辨率都是正常使用的。摄像头是双目的卷帘，之前试过2560*960的双目卷帘也是正常的。是因为分辨率太高了导致这个问题的吗。用的mpp硬解码实现mjpeg解码。

**Comment by HermanChen** [comment]
输入 buffer 高度16对齐的问题

**Comment by Lizi633** [comment]
什么意思？能详细说一下吗

**Comment by HermanChen** [comment]
vepu2 的 jpeg 编码器要求输入的 hor_stride 16 对齐
