### ISSUE TITLE
mpp 拷贝解码后的数据 速度很慢

### ISSUE THREAD

**Issue by giwhy** [rockchip-linux/mpp#67]
你好，我有个问题，我对mpp解码后的数据进行一个拷贝的时候发现花费的时间异常的高，拷贝一帧1920x1080的yuv数据 时间长达40ms ，好像是ion分配出来的内存会这样， 测试malloc 出同样大小的内存进行拷贝测试， 花费不到5ms。 我是在rk3328 、3.10内核 上测试。  请问这是什么原因，有没有什么解决方案。

**Comment by HermanChen** [comment]
ion 内存是专门给硬件访问使用的，因为一致性问题，默认配置是 non-cache 的，cpu 访问是会比较慢的。malloc 的缓存是分配给 cpu 访问的的，默认都是 cachable 的。两者的访问速度本身就区别很大。

**Comment by giwhy** [comment]
是的，我把ION_IOC_ALLOC  时候的flags改为1的时候  速度确实很快，  但是数据也是不对的，请问内核中有相应的接口 或者 mpp 中的接口让 我进行 invalide操作吗。 好像老版本ion驱动中有这么一个接口cache_op，我现在的内核中ion那块找不到这个接口。因为软件功能上的限制，我不得已进行这个操作，可以提供下大致的思路给我吗，十分感谢。

**Comment by HermanChen** [comment]
老版本的非标 RK 版本是有的，现在标准的 Android 内核上没有了

**Comment by HermanChen** [comment]
要用的话，估计要在内核里加上解码输出 buffer 的自动 invalid 处理

**Comment by giwhy** [comment]
可以把自动invalid 处理的那块代码给我吗 ， 我给它加上去。

**Comment by giwhy** [comment]
outer_inv_range，dmac_inv_range  ，是这两个函数吗？

**Comment by HermanChen** [comment]
是的

**Comment by fuckdk** [comment]
> outer_inv_range，dmac_inv_range ，是这两个函数吗？

请问你解决了吗

**Comment by giwhy** [comment]
我的解决方法是(没用outer_inv_range):
解码前的buf 一定是无cache 的(不然解码出错) ,解决办法是把解码后的buf 设置成 有cache的(可能会有一点点的数据不一样,几乎可以忽略,除非图片非常小才会有那些一小根一小根的黑线) , 这样拷贝速度就正常了 1920x1080 bgra 拷贝速度是 13ms左右吧具体看芯片平台. 也可以把rga嵌进去,直接用rga 拷贝到有cache的内存 ,顺便还能转码缩放之类的,这个没实践过.

在 2019-01-09 14:10:48，"epcdiy" <notifications@github.com> 写道：


outer_inv_range，dmac_inv_range ，是这两个函数吗？

请问你解决了吗

**Comment by haithink** [comment]
> 解决办法是把解码后的buf 设置成 有cache

请问具体怎么做的呢？谢谢
