### ISSUE TITLE
为什么有些函数找不到它的实现？

### ISSUE THREAD

**Issue by GOAWAY88** [rockchip-linux/mpp#674]
例如：mpp_frame_get_info_change函数，我在mpp中没有找到它的底层实现原理。不知道该怎么看呢？

**Comment by HermanChen** [comment]
https://github.com/rockchip-linux/mpp/blob/e9d95ce4a55271499bb8ca07d72a897540f43bb4/mpp/base/mpp_frame.cpp#L297
