### ISSUE TITLE
怎么输出全部的库文件和头文件

### ISSUE THREAD

**Issue by GOAWAY88** [rockchip-linux/mpp#678]
我执行了make-Android.bash，编译了mpp，但是没有头文件和库文件的集合，为啥库文件都是零散的分布在各个文件夹中呢？inc中的头文件好像也不全哦

**Comment by HermanChen** [comment]
对外头文件在最上层的 inc 里，外部用户不需要使用到这个目录之外的头文件

**Comment by GOAWAY88** [comment]
> 对外头文件在最上层的 inc 里，外部用户不需要使用到这个目录之外的头文件

那库文件呢？我看有libmpp.so，还有其他libvpu.so，需要使用libvpu.so吗？

**Comment by HermanChen** [comment]
libvpu.so 是兼容老的 vpu_api.so 代码的，现在已经不需要了
