### ISSUE TITLE
关于编译后部分函数使用疑惑

### ISSUE THREAD

**Issue by pan1024** [rockchip-linux/mpp#682]
在编译完成MPP并make install后类似mpi_dec_utils.c等只打包为.a以及对应的头文件没有install到目标文件夹，某些函数类似dec_buf_mgr_setup、dec_buf_mgr_init如何使用

**Comment by HermanChen** [comment]
utils 里的函数不是 mpp 库本体里，是服务于 test case 的，外部如果要用的话，可以拷贝到外部使用
