### ISSUE TITLE
Does the JPEG encoder on rk3576 support RGB formats?

### ISSUE THREAD

**Issue by nyanmisaka** [rockchip-linux/mpp#687]
Does the JPEG encoder on rk3576 support RGB formats?

For the HAL (vpu720), it seems like it is not supported or not implemented yet.
https://github.com/rockchip-linux/mpp/blob/05b809393c41120c81fbdb39356b01c92aa77907/mpp/hal/rkenc/jpege/hal_jpege_vpu720.c#L232-L313

**Comment by HermanChen** [comment]
yes, the jpeg encoder on rk3576 is a costdown standalone version. The color conversion preprocess is almost the same size as the jpeg encoder. So IC remove the color conversion module before jpeg encoder.

**Comment by nyanmisaka** [comment]
Thx for the info.
