### ISSUE TITLE
h264 slice size

### ISSUE THREAD

**Issue by Warpmh** [rockchip-linux/mpp#69]
Hi,

I try set slice size with h264 encoder on orange pi rk3399(Debian 9 4.4.103 #2 SMP Tue Oct 16 14:39:05 CST 2018 aarch64 GNU/Linux).  Structure MppEncCodecCfg has two elements slice_mode and slice_arg , howto set they properly to get slices <= some value?

Best Regards,
Warp.

**Comment by xueshenan** [comment]
Five years have passed, still no reply. Seems rk mpp not support slice encode.

**Comment by HermanChen** [comment]
The slice mode had been supported for years
https://github.com/rockchip-linux/mpp/blob/e34f0dd1520181eda061f91883c670504432fb8f/inc/rk_venc_cmd.h#L976
