### ISSUE TITLE
Which decoder framework is best for MJPEG?

### ISSUE THREAD

**Issue by srimanachanta** [rockchip-linux/mpp#692]
Hello, I am writing a V4L2 memory-to-memory stateless decoder to decode (usually MJPEG) camera frames and am trying to use mpp to handle decode of the frames. I notice there are two examples for this, one which is single threaded and one which is multithreaded. When should I use which one? Which one should I use if I want the absolute best performances for my project?

Thanks for any insight on this question

**Comment by HermanChen** [comment]
jpeg decoder only can use the enqueue / dequeue flow in mpi_dec_test.
When using non-jpeg decoder use the flow in mpi_dec_mt_test is better.

**Comment by srimanachanta** [comment]
Thanks, follow up question,
