### ISSUE TITLE
通过opencv叠加的直线经过MPP后出现粗细不一致的情况

### ISSUE THREAD

**Issue by Linuxliuzhe** [rockchip-linux/mpp#699]
请问一下通过opencv叠加的直线不同位置，边缘像素的rgb值变化很大，导致视频看起来有粗细变化，这个是什么的原因，HDMI直出的就不会有变化

**Comment by Linuxliuzhe** [comment]
采用的H265编码

**Comment by Linuxliuzhe** [comment]
采用的H265编码

**Comment by HermanChen** [comment]
这应该主要是 444 转 420 时候角度下采样出来的伪彩色

**Comment by Linuxliuzhe** [comment]
> 这应该主要是 444 转 420 时候角度下采样出来的伪彩色

我是先通过opencv将图像数据转化为CV_8UC3格式，再画线，然后通过mpp编码网络输出，mpp配置的色彩格式是bgr888，这样会出现伪色彩吗？主要现象是画线每次移动一个像素就会发生粗细变化，然后变化几乎一致都是变粗变回去然后再变粗，移动两个像素就不会出现变化

**Comment by HermanChen** [comment]
mpp 编码的时候，都会自动转成 YUV420，这里就存在色度下采样，会出现伪彩色问题

**Comment by Linuxliuzhe** [comment]
感谢，最后找到问题了，是因为opencv叠加的东西，给的色彩值是0，255，0，导致色彩对比度太高，经过mpp后锐化程度过高，才出现的这个现象，在压缩前增加一次模糊处理就好很多了
