### ISSUE TITLE
How to convert from MJPEG to YUV422SP?

### ISSUE THREAD

**Issue by dmitry1945** [rockchip-linux/mpp#70]
HI All,

I have TinkerBoard with RK3288.
I need to decode data from USB camera, that provides data in MJPEG toYUV422SP format and then process it. 
I use mpi_dec_test to decode the jpeg image from file to other file. The command line is next:
./test/mpi_dec_test -i /home/linaro/apps/test1.jpg -o test_my.bmp -w 1280 -h 720 -t 8 -f 2-d 1

I have tried to convert MJPEG 2 YUV422SP  and got a problem. The trace below.
It looks like slot have default resolution 640x480 and it's not changed even if input frame resulution 1280x720.

What do I wrong? Is it bug or feature?
Regards,
Dmitry

./test/mpi_dec_test -i /home/linaro/apps/test1.jpg -o test_my.bmp -w 1280 -h 720 -t 8 -f 2 -d 1
mpi_dec_test: cmd parse result:
mpi_dec_test: input  file name: /home/linaro/apps/test1.jpg
mpi_dec_test: output file name: test_my.bmp
mpi_dec_test: config file name:
mpi_dec_test: width      : 1280
mpi_dec_test: height     :  720
mpi_dec_test: type       : 8
mpi_dec_test: debug flag : 1
mpi_dec_test: max frames : 0
mpi_dec_test: mpi_dec_test start
mpi_dec_test: input file size 37495
mpp_rt: NOT found ion allocator
mpp_rt: found drm allocator
mpi_dec_test: mpi_dec_test decoder test start w 1280 h 720 type 8
mpi: mpp_create enter ctx 0xbe91d170 mpi 0xbe91d16c
mpi: mpp version: 1babbc9c author: Ding Wei [h264d]: fix bug: fast output frame
mpi: mpp_create leave ret 0 ctx 0x7ff83da0 mpi 0xb6f4bf50
mpi: mpi_control enter ctx 0x7ff83da0 cmd 310005 parm 0xbe91d160
mpi: mpi_control leave ret 0
mpi: mpp_init enter ctx 0x7ff83da0 type 0 coding 8
mpp_buf_slot: slot 0x7ff84340 setup: count 2
mpp_buf_slot: slot   1 index  0 op: init            arg      (nil) status in 00000000 out 00000000
mpp_buf_slot: slot   1 index  1 op: init            arg      (nil) status in 00000000 out 00000000
mpp_buf_slot: slot 0x7ff840a0 setup: count 1
mpp_buf_slot: slot   0 index  0 op: init            arg      (nil) status in 00000000 out 00000000
jpegd_parser: jpegd_init exit
HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_init enter
HAL_JPEGD_VDPU1: jpegd_regs_init enter
HAL_JPEGD_VDPU1: jpegd_regs_init exit
HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_init exit
mpi: mpp_init leave ret 0
mpi: mpi_control enter ctx 0x7ff83da0 cmd 31000a parm 0xbe91d4c0
jpegd_parser: jpegd_control enter
jpegd_parser: output_format:2
jpegd_parser: jpegd_control exit
HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_control enter
HAL_JPEGD_VDPU1: output_format:2
HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_control exit
mpi: mpi_control leave ret 0
mpi: mpi_poll enter ctx 0x7ff83da0 type 0 timeout -1
mpi: mpi_poll leave ret 0
mpi: mpi_dequeue enter ctx 0x7ff83da0 type 0 task 0xbe91d0d4
mpi: mpi_dequeue leave ret 0
mpi: mpi_enqueue enter ctx 0x7ff83da0 type 0 task 0x7ff86880
mpi: mpi_enqueue leave ret 0
mpi: mpi_poll enter ctx 0x7ff83da0 type 1 timeout -1
jpegd_parser: jpegd_prepare enter
jpegd_parser: pkt_length 37495 eos 0
jpegd_parser: jpegd_split_frame enter
jpegd_parser: jpegd_split_frame exit
jpegd_parser: input_packet:0x7ff84920, recv_buffer:0xb6b07020, pkt_length:37495
jpegd_parser: jpegd_prepare exit
mpp_buf_slot: slot   1 index  0 op: set on use      arg      (nil) status in 00000000 out 00000001
mpp_buf_slot: slot   1 index  0 op: set not ready   arg      (nil) status in 00000001 out 00000003
mpp_buf_slot: slot   1 index  0 op: set buffer      arg 0x7ff83c60 status in 00000003 out 00040003
mpp_buf_slot: slot   1 index  0 op: set codec ready arg      (nil) status in 00040003 out 00040001
mpp_buf_slot: slot   1 index  0 op: set hal input   arg      (nil) status in 00040001 out 00040011
jpegd_parser: jpegd_parse enter
jpegd_parser: jpegd_decode_frame enter
jpegd_parser: find_marker skipped 0 bytes
jpegd_parser: marker = 0xd8, avail_size_in_buf = 37493, buf_size = 37495
jpegd_parser: find_marker skipped 0 bytes
jpegd_parser: marker = 0xe0, avail_size_in_buf = 37491, buf_size = 37495
jpegd_parser: mjpeg: JFIF header found (version: 1.1) SAR=1/1
jpegd_parser: unhandled coding type(0xe0) in switch..case..
jpegd_parser: find_marker skipped 16 bytes
jpegd_parser: marker = 0xdb, avail_size_in_buf = 37473, buf_size = 37495
jpegd_parser: quantize tables ID=0
jpegd_parser:
******Start to print quantize table 0******

0x0a,0x07,0x07,0x08,0x07,0x06,0x0a,0x08,
0x08,0x08,0x0b,0x0a,0x0a,0x0b,0x0e,0x18,
0x10,0x0e,0x0d,0x0d,0x0e,0x1d,0x15,0x16,
0x11,0x18,0x23,0x1f,0x25,0x24,0x22,0x1f,
0x22,0x21,0x26,0x2b,0x37,0x2f,0x26,0x29,
0x34,0x29,0x21,0x22,0x30,0x41,0x31,0x34,
0x39,0x3b,0x3e,0x3e,0x3e,0x25,0x2e,0x44,
0x49,0x43,0x3c,0x48,0x37,0x3d,0x3e,0x3b,jpegd_parser:
******Quantize table 0 End******

jpegd_parser: qscale[0]: 4
jpegd_parser: find_marker skipped 67 bytes
jpegd_parser: marker = 0xdb, avail_size_in_buf = 37404, buf_size = 37495
jpegd_parser: quantize tables ID=1
jpegd_parser:
******Start to print quantize table 1******

0x0a,0x0b,0x0b,0x0e,0x0d,0x0e,0x1c,0x10,
0x10,0x1c,0x3b,0x28,0x22,0x28,0x3b,0x3b,
0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,
0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,
0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,
0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,
0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,
0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,0x3b,jpegd_parser:
******Quantize table 1 End******

jpegd_parser: qscale[1]: 8
jpegd_parser: find_marker skipped 67 bytes
jpegd_parser: marker = 0xc0, avail_size_in_buf = 37335, buf_size = 37495
**jpegd_parser: sof0: picture: 640x480, stride: 640x480**
jpegd_parser: component 0 2:2 id: 0 quant_id:0
jpegd_parser: component 1 1:1 id: 1 quant_id:1
jpegd_parser: component 2 1:1 id: 2 quant_id:1
jpegd_parser: YCbCr Format: YUV420(2*2:1*1:1*1)
jpegd_parser: find_marker skipped 17 bytes
jpegd_parser: marker = 0xc4, avail_size_in_buf = 37316, buf_size = 37495
jpegd_parser: dht: huffman tables length=29
jpegd_parser: dht: type=0 id=0 code_word_num=12, code_max=11, len=0
jpegd_parser: find_marker skipped 31 bytes
jpegd_parser: marker = 0xc4, avail_size_in_buf = 37283, buf_size = 37495
jpegd_parser: dht: huffman tables length=179
jpegd_parser: dht: type=1 id=0 code_word_num=162, code_max=250, len=0
jpegd_parser: find_marker skipped 181 bytes
jpegd_parser: marker = 0xc4, avail_size_in_buf = 37100, buf_size = 37495
jpegd_parser: dht: huffman tables length=29
jpegd_parser: dht: type=0 id=1 code_word_num=12, code_max=11, len=0
jpegd_parser: find_marker skipped 31 bytes
jpegd_parser: marker = 0xc4, avail_size_in_buf = 37067, buf_size = 37495
jpegd_parser: dht: huffman tables length=179
jpegd_parser: dht: type=1 id=1 code_word_num=162, code_max=250, len=0
jpegd_parser: find_marker skipped 181 bytes
jpegd_parser: marker = 0xda, avail_size_in_buf = 36884, buf_size = 37495
jpegd_parser: sos component: 0
jpegd_parser: component:0, dc_index:0, ac_index:0
jpegd_parser: sos component: 1
jpegd_parser: component:1, dc_index:1, ac_index:1
jpegd_parser: sos component: 2
jpegd_parser: component:2, dc_index:1, ac_index:1
jpegd_parser: This packet owns 37495 bytes,
                has been decoded 623 bytes by software
                buf_ptr:0xb6b07283, buf:0xb6b07020, sos_len:12
                hardware start address:0xb6b0728f
jpegd_parser: input img maybe png format,check it
jpegd_parser: find_marker skipped 36882 bytes
jpegd_parser: marker = 0xd9, avail_size_in_buf = 0, buf_size = 37495
jpegd_parser: still exists 0 bytes behind EOI marker
jpegd_parser: jpegd_decode_frame exit
jpegd_parser: jpegd_allocate_frame enter
mpp_buf_slot: slot   0 index  0 op: set on use      arg      (nil) status in 00000000 out 00000001
mpp_buf_slot: slot   0 index  0 op: set not ready   arg      (nil) status in 00000001 out 00000003
jpegd_parser: frame_slot_index:0
mpp_buf_slot: slot   0 index  0 op: set frame       arg 0x7ff849a0 status in 00000003 out 00080003
mpp_buf_slot: slot   0 index  0 op: set codec use   arg      (nil) status in 00080003 out 00080007
mpp_buf_slot: slot   0 index  0 op: set hal output  arg      (nil) status in 00080007 out 0008000f
jpegd_parser: jpegd_allocate_frame exit
jpegd_parser: jpegd_update_frame enter
mpp_buf_slot: slot   0 index  0 op: clr codec use   arg      (nil) status in 0008000f out 0008000b
jpegd_parser: jpegd_update_frame exit
jpegd_parser: jpegd_parse exit
**mpp_dec: mpp_dec_advanced_thread slot size 614400 is not equal to buffer size 3686400**
mpp_dec: Assertion slot_size == buffer_size failed at mpp_dec_advanced_thread:1080
mpp_buf_slot: slot   0 index  0 op: set buffer      arg 0x7ff83ba0 status in 0008000b out 000c000b
HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_gen_regs enter
HAL_JPEGD_COMMON: jpegd_setup_output_fmt enter
HAL_JPEGD_COMMON: Post Process! pp_in_fmt:1, pp_out_fmt:5
HAL_JPEGD_COMMON: jpegd_setup_output_fmt exit
HAL_JPEGD_VDPU1: mpp_device_init success.
HAL_JPEGD_VDPU1: jpegd_setup_pp enter
HAL_JPEGD_VDPU1: jpegd_set_extra_info enter
HAL_JPEGD_VDPU1: jpegd_set_extra_info exit
HAL_JPEGD_VDPU1: outLumaBuffer:7, ch reg67:7
HAL_JPEGD_VDPU1: jpegd_setup_pp exit
HAL_JPEGD_VDPU1: jpegd_gen_regs enter
HAL_JPEGD_VDPU1: jpegd_write_code_word_number enter
HAL_JPEGD_VDPU1: jpegd_write_code_word_number exit
HAL_JPEGD_COMMON: jpegd_write_qp_ac_dc_table enter
HAL_JPEGD_COMMON: jpegd_write_qp_ac_dc_table exit
HAL_JPEGD_VDPU1: jpegd_set_chroma_table_id enter
HAL_JPEGD_VDPU1: jpegd_set_chroma_table_id exit
HAL_JPEGD_VDPU1: jpegd_set_stream_offset enter
HAL_JPEGD_VDPU1: jpegd_set_stream_offset exit
HAL_JPEGD_VDPU1: jpegd_gen_regs exit
HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_gen_regs exit
HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_start enter
HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_start exit
HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_wait enter
HAL_JPEGD_VDPU1: DECODE SUCCESS!
HAL_JPEGD_VDPU1: frame_00 output YUV(640*480) saving to /tmp/output00.yuv
HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_wait exit
mpp_buf_slot: slot   1 index  0 op: clr hal input   arg      (nil) status in 00040011 out 00040001
mpp_buf_slot: slot   1 index  0 op: clr buffer      arg 0x7ff83c60 status in 00040001 out 00000001
mpp_buf_slot: slot   1 index  0 op: clr on use      arg      (nil) status in 00000001 out 00000000
mpp_buf_slot: slot   0 index  0 op: clr hal output  arg      (nil) status in 000c000b out 000c0001
mpp_buf_slot: slot   0 index  0 op: clr frame       arg 0xb62005c0 status in 000c0001 out 00040001
mpp_buf_slot: slot   0 index  0 op: clr buffer      arg 0x7ff83ba0 status in 00040001 out 00000001
mpp_buf_slot: slot   0 index  0 op: clr on use      arg      (nil) status in 00000001 out 00000000
mpi: mpi_poll leave ret 0
mpi: mpi_dequeue enter ctx 0x7ff83da0 type 1 task 0xbe91d0d4
mpi: mpi_dequeue leave ret 0
mpi_dec_test: decoded frame 1
mpi: mpi_enqueue enter ctx 0x7ff83da0 type 1 task 0x7ff86960
mpi: mpi_enqueue leave ret 0
mpi_dec_test: found last packet
mpi: mpi_poll enter ctx 0x7ff83da0 type 0 timeout -1
mpi: mpi_poll leave ret 0
mpi: mpi_dequeue enter ctx 0x7ff83da0 type 0 task 0xbe91d0d4
mpi: mpi_dequeue leave ret 0
mpi: mpi_enqueue enter ctx 0x7ff83da0 type 0 task 0x7ff86880
mpi: mpi_enqueue leave ret 0
mpi: mpi_poll enter ctx 0x7ff83da0 type 1 timeout -1
jpegd_parser: jpegd_prepare enter
jpegd_parser: pkt_length 0 eos 1
jpegd_parser: it is end of stream.
mpi: mpi_poll leave ret 0
mpi: mpi_dequeue enter ctx 0x7ff83da0 type 1 task 0xbe91d0d4
mpi: mpi_dequeue leave ret 0
mpi_dec_test: decoded frame 2
mpi_dec_test: found eos frame
mpi: mpi_enqueue enter ctx 0x7ff83da0 type 1 task 0x7ff86960
mpi: mpi_enqueue leave ret 0
mpi: mpi_reset enter ctx 0x7ff83da0
mpi: mpi_reset leave ret 0
mpi: mpp_destroy enter ctx 0x7ff83da0
jpegd_parser: jpegd_deinit enter
jpegd_parser: jpegd_deinit exit
HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_deinit enter
HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_deinit exit
mpi: mpp_destroy leave ret 0
mpi_dec_test: test success max memory 0.00 MB

**Comment by WainDing** [comment]
目前驱动是默认，输出为nv12。

**Comment by guanglefeng** [comment]
@WainDing  请问rk的mjpeg硬件解码输出格式都是固定nv12么？没有其他格式可以输出么？

**Comment by WainDing** [comment]
目前是只支持NV12，如果需要支持YUV422SP，需要级联别的IP实现

**Comment by guanglefeng** [comment]
@WainDing 回复这么快 谢谢你的解答。
另外借用这个问题，问一下
如果我解码mjpeg的话，并且需要同步得到解码图像，是不是应该把 MPP_DEC_SET_PARSER_SPLIT_MODE 设置为0 ，因为jpeg一般都是完整一帧而不是码流。
然后调用 (*decode)(MppCtx ctx, MppPacket packet, MppFrame *frame) 来同步传入数据获取解码图像？
这样的话，会延迟一帧还是会立即得到结果？

**Comment by WainDing** [comment]
如果送入的每个packet都能保证是完整的一帧的话，可以设置为0。

**Comment by guanglefeng** [comment]
@WainDing 明白
请问有
 (*decode)(MppCtx ctx, MppPacket packet, MppFrame *frame)
这个接口的sample么？
用这个接口，我不理解怎么实现纯内部模式，如果返回的frame有 info change信息，后续怎么再次获取frame，因为packet已经送过一次了，所以不明白怎么单独使用这个接口

**Comment by WainDing** [comment]
test目录下，有个mpi_dec_test可以参考下

**Comment by guanglefeng** [comment]
@WainDing 
好的，这个mpi_dec_test例子我结合文档反复看了很多遍了
不过里面并没有调用decode这个api。:(
我再看看试试吧，就不叨扰你了，谢谢你的解答。
