### ISSUE TITLE
现有的mpp库中自带的rga静态库能否使用

### ISSUE THREAD

**Issue by shi156** [rockchip-linux/mpp#706]
当我按照示例在frame编码前进行rga缩放，最后传递出来的数据是异常的，视频帧描述:色块混乱，重影。
3840*2160转1920*1080就会出现，不管是比例还是非比例缩放都是不可以的，只有一比一拷贝正常，4k消耗的时间大约100ms，希望官方可以解答！！！

**Comment by HermanChen** [comment]
不用用 mpp 里的 rga……用 librga 里的

**Comment by shi156** [comment]
好的，明白了，无语死了，在mpp中的vproc中的rga搞了几天，一直都有问题，为什么不删了呢...
感谢大佬！

**Comment by HermanChen** [comment]
历史原因……
