### ISSUE TITLE
mpp轮询开关多路解码，遇到mpp库段错误

### ISSUE THREAD

**Issue by mojiaj** [rockchip-linux/mpp#726]
我做了一个应用，5s循环开启30路1080P30解码（具体操作为初始化mppdec，开始解码，反初始化mppdec）
该程序运行一段时间之后，会产生段错误
使用的mpp库是github上的release版本V1.0.5
错误日志为：
Dec  2 11:50:06 user.err mpp[21609]: mpp_dma_heap: mmap failed: Operation not permitted
Dec  2 11:50:06 user.err mpp[21609]: mpp_buffer: mpp_buffer_mmap buffer 0 group 36904 fd 731 map failed caller try_proc_dec_task
Dec  2 11:50:06 user.err mpp[21609]: mpp_buffer: Assertion dst != __null failed at mpp_buffer_write_with_caller:160
Dec  2 11:50:06 user.err mpp[21609]: mpp_log: mpp_dmabuf_sync_end ioctl failed for Inappropriate ioctl for device from try_proc_dec_task
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 13796 get used:unused [0:0] from mpp_hevc_decode_nal_sps
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 224 get used:unused [1135:269] from mpp_frame_init
Dec  2 11:50:06 user.info mpp[21609]: mpp_buf_slot: new width 1920 height 1080 stride hor 1920 ver 1080 fmt    0
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 224 get used:unused [1136:268] from mpp_frame_init
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 288 get used:unused [217:45] from DP_CMPI_VDEC_PTH_MallocDma
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 240 get used:unused [257:309] from DP_CMPI_VDEC_PTH_MallocDma
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 240 get used:unused [258:308] from DP_CMPI_VDEC_PTH_MallocDma
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 240 get used:unused [259:307] from DP_CMPI_VDEC_PTH_MallocDma
Dec  2 11:50:06 user.info mpp[21609]: mpp: using external buffer group (nil)
Dec  2 11:50:06 user.info mpp[21609]: mpp: set info change ready
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 224 put used:unused [1137:267] from mpp_frame_deinit
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 88 put used:unused [2:92] from check_entry_unused
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 288 get used:unused [218:44] from hal_bufs_init
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 224 put used:unused [1136:268] from mpp_frame_deinit
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 240 get used:unused [260:306] from hal_bufs_get_buf
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 224 get used:unused [1135:269] from mpp_frame_init
Dec  2 11:50:06 user.err mpp[21609]: mpp_dma_heap: mmap failed: Operation not permitted
Dec  2 11:50:06  user.err mpp[21609]: mpp_buffer: mpp_buffer_mmap buffer 0 group 36904 fd 731 map failed caller hal_h265d_vdpu34x_gen_regs
Dec  2 11:50:06 user.err mpp[21609]: mpp_buffer: Assertion p->info.ptr != __null failed at mpp_buffer_get_ptr_with_caller:178
Dec  2 11:50:06 user.err mpp[21609]: mpp_buffer: mpp_buffer_get_ptr buffer 0x7db003b3a8 ret NULL from hal_h265d_vdpu34x_gen_regs
Dec  2 11:50:06 user.info mpp[21609]: mpp_mem_pool: pool 224 put used:unused [1136:268] from mpp_frame_deinit

请问一下，这个问题要怎样排查，有可能是什么原因导致的

**Comment by HermanChen** [comment]
fd 731 感觉 buffer 用得比较多 mpp_buffer_mmap  失败有可能是 4G 虚存都用光了？

**Comment by HermanChen** [comment]
fd 731 感觉 buffer 用得比较多 mpp_buffer_mmap  失败有可能是 4G 虚存都用光了？

**Comment by mojiaj** [comment]
好的，谢谢，我检查一下虚拟内存的使用，但是有一次我看到的现象好像是返回-22，这个也是虚拟内存不够的问题吗
 mpp_serivce: mpp_service_ioc_attach_fd failed ret -1 errno 22 Invalid argument
Dec  3 07:06:45 user.err mpp[20731]: mpp_dma_heap: mmap failed: Bad file descriptor
Dec  3 07:06:45 user.err mpp[20731]: mpp_buffer: mpp_buffer_mmap buffer 0 group 7433 fd 444 map failed caller try_proc_dec_task
Dec  3 07:06:45 user.err mpp[20731]: mpp_buffer: Assertion dst != __null failed at mpp_buffer_write_with_caller:160
Dec  3 07:06:45 user.err mpp[20731]: mpp_log: mpp_dmabuf_sync_end ioctl failed for Bad file descriptor from try_proc_dec_task
Dec  3 07:06:45 user.err mpp[20731]: mpp_dma_heap: mmap failed: Invalid argument
Dec  3 07:06:45 user.err mpp[20731]: mpp_buffer: mpp_buffer_mmap buffer 0 group 7433 fd 444 map failed caller hal_h265d_vdpu34x_gen_regs
Dec  3 07:06:45 user.err mpp[20731]: mpp_buffer: Assertion p->info.ptr != __null failed at mpp_buffer_get_ptr_with_caller:178
Dec  3 07:06:45 user.err mpp[20731]: mpp_buffer: mpp_buffer_get_ptr buffer 0x7e30012288 ret NULL from hal_h265d_vdpu34x_gen_regs
Dec  3 07:06:45 kern.err kernel: [12861.149128] mpp_dma_import_fd:210: dma_buf_get fd 444 failed(-9)
Dec  3 07:06:45 kern.err kernel: [12861.149136] rk_vcodec: mpp_process_request:1374: can not import fd 444
Dec  3 07:06:45 kern.err kernel: [12861.149139] rk_vcodec: mpp_collect_msgs:1562: session 3535 process cmd 401 ret -22
Dec  3 07:06:45 kern.err kernel: [12861.149141] rk_vcodec: mpp_dev_ioctl:1672: collect msgs failed -22

**Comment by HermanChen** [comment]
文件句柄不对？还是说内核比较老，不支持 attach 这个 ioctl？

**Comment by mojiaj** [comment]
程序正常是可以跑起来一段时间的，内核是5.1版本的。如果应用程序有内存越界的话，也会影响这个的吗？这个好像是mpp内部申请的buffer

**Comment by HermanChen** [comment]
应用程序有内存越界会有影响，传一份完整的从开始到出问题的 log，放到网盘或者其他地方

**Comment by mojiaj** [comment]
要开日志等级这些吗？好像日志文件大小有限制，有可能会冲掉

**Comment by HermanChen** [comment]
开串口终端，然后终端写文件？

**Comment by HermanChen** [comment]
另外，not permit 的话，用 root 跑下看看

**Comment by mojiaj** [comment]
好的

**Comment by mojiaj** [comment]
[var_log_messag.log](https://github.com/user-attachments/files/18001025/var_log_messag.log)
[串口.log](https://github.com/user-attachments/files/18001028/default.log)
0x0000007ff4a08018 in __memset_generic () from /lib/libc.so.6
(gdb) bt
#0  0x0000007ff4a08018 in __memset_generic () from /lib/libc.so.6
#1  0x0000007ff7e197a4 in hal_h265d_vdpu34x_gen_regs () from /lib/librockchip_mpp.so.1
#2  0x0000007ff7d67778 in mpp_dec_parser_thread(void*) () from /lib/librockchip_mpp.so.1
#3  0x0000007ff49f0958 in start_thread () from /lib/libc.so.6
#4  0x0000007ff4a4609c in thread_start () from /lib/libc.so.6

**Comment by HermanChen** [comment]
码流是有错的吧，解码器一段时间会报一下错，后面 410 fd 开始有问题，应该是上层哪里错关了 fd 导致的？

**Comment by mojiaj** [comment]
码流是一直丢包导致的，问题找到啦，应用程序有地方越界了，非常感谢
