### ISSUE TITLE
rk3588s 支持单路8k30帧编码吗,目前我测试单路8k编码只有15fps.

### ISSUE THREAD

**Issue by 2398tr** [rockchip-linux/mpp#728]
rk3588s 支持单路8k30帧编码吗，目前我测试单路8k编码只有15fps.

**Comment by HermanChen** [comment]
用 mpi_enc_mt_test 来跑

**Comment by 2398tr** [comment]
mpi_enc_mt_test  我测试了一下h265能达到30fps，h264不能，正确的应该是这样的对吗

**Comment by HermanChen** [comment]
看硬件时间 echo 0x100 > /sys/module/rk_vcodec/parameters/mpp_dev_debug

**Comment by 2398tr** [comment]
我就是看到硬件时间 h264 50多ms h265接近30ms

**Comment by HermanChen** [comment]
是的，264 的性能是 265 一半

**Comment by 2398tr** [comment]
好的谢谢
