### ISSUE TITLE
mpp_buffer_import 导入的buffer如何销毁

### ISSUE THREAD

**Issue by 2398tr** [rockchip-linux/mpp#733]
mpp_buffer_import 导入的buffer如何销毁

**Comment by HermanChen** [comment]
mpp_buffer_import 导入生成的 buffer 用 mpp_buffer_put 销毁，原始 buffer 用原始 buffer 的销毁方法销毁，两个是独立的

**Comment by 2398tr** [comment]
好的谢谢
