### ISSUE TITLE
MPP在RK3528上的支持

### ISSUE THREAD

**Issue by Choise-ieee** [rockchip-linux/mpp#738]
我在RK3528的rockpi2A的debian系统安装了最新的mpp-1.0.7
然后make和makeinstall均通过
然后执行mpp_info_test没有打印，在var/log/syslog中也没有打印
想问问是不是因为mpp在3528上没有适配导致的呢，谢谢

**Comment by HermanChen** [comment]
export mpp_syslog_perror=1
