### ISSUE TITLE
H264 encoder fail when gop size is 0

### ISSUE THREAD

**Issue by ruanjiandong** [rockchip-linux/mpp#76]
when gop size is set to zero, H264 encoder doesn't produce any output: self->mpi->dequeue (self->mpp_ctx, MPP_PORT_OUTPUT, &task)) always fails.

Also, the following error is logged:
mpp_rc: mpp_data_init invalid data 1433094992ata size 0
mpp_rc: mpp_data_init invalid data 1433095008ata size 0
mpp_rc: mpp_data_init invalid data 1433095016ata size 0
mpp_rc: mpp_data_init invalid data 1433096560ata size 0

**Comment by JeffyCN** [comment]
fixed
