### ISSUE TITLE
关于jpeg 图片的解码速度

### ISSUE THREAD

**Issue by giwhy** [rockchip-linux/mpp#77]
您好
mpi_dec_test 解码一帧较高质量的jpeg 图片  需要55ms  请问这个解码时间是否正常，
=========下面是计算时间代码块=======
    int stime = tf_getcurtime(0);
    ret = mpi->poll(ctx, MPP_PORT_INPUT, MPP_POLL_BLOCK);
    if (ret) {
        mpp_err("mpp input poll failed\n");
        return ret;
    }

    ret = mpi->dequeue(ctx, MPP_PORT_INPUT, &task);  /* input queue */
    if (ret) {
        mpp_err("mpp task input dequeue failed\n");
        return ret;
    }

    mpp_assert(task);

    mpp_task_meta_set_packet(task, KEY_INPUT_PACKET, packet);
    mpp_task_meta_set_frame (task, KEY_OUTPUT_FRAME,  frame);

    ret = mpi->enqueue(ctx, MPP_PORT_INPUT, task);  /* input queue */
    if (ret) {
        mpp_err("mpp task input enqueue failed\n");
        return ret;
    }

    /* poll and wait here */
    ret = mpi->poll(ctx, MPP_PORT_OUTPUT, MPP_POLL_BLOCK);
    if (ret) {
        mpp_err("mpp output poll failed\n");
        return ret;
    }

    ret = mpi->dequeue(ctx, MPP_PORT_OUTPUT, &task); /* output queue */
    if (ret) {
        mpp_err("mpp task output dequeue failed\n");
        return ret;
    }
    printf("======time = %d \n",tf_getcurtime(0) - stime);

**Comment by HermanChen** [comment]
这个时间的确是上层看到的时候，要准确的看硬件时间，需要在内核看
vpu 的标称 jpeg 解码能力是 90M pixel / s，可以对比解码的图像大小看一下。
