### ISSUE TITLE
请问下3399的android板子能用这个MPP解码6路1080P吗？，我直接用mediacodec好像不行

### ISSUE THREAD

**Issue by yuan631111976** [rockchip-linux/mpp#78]

**Comment by WainDing** [comment]
3399???

**Comment by yuan631111976** [comment]
RK3399,打错了

**Comment by WainDing** [comment]
MPP没有对解码路数限制，但mediacodec，应该有可能做限制。

**Comment by yuan631111976** [comment]
哦哦，那3399的android板子是有能力用这个MPP解6路1080P的，是吗？

**Comment by WainDing** [comment]
帧率要求多少？什么场景的应用？能支持到什么程度，需实测。理论上，6路30fps的花，已经很极限了。

**Comment by yuan631111976** [comment]
6路1080P ,25到30帧，还需要用OPENGL把这六路绘制到一张纹理上面，也是1080P，然后再硬编码，不是知道android的rk3399能不能带得动？6路是实时的，会一直不停地解码，不会断！视频监控这类的场景

**Comment by WainDing** [comment]
如果还要编码的花，这样的场景，支持不下来。

**Comment by yuan631111976** [comment]
那我可以减少路数，只需要解五路之类的，非常感谢您！

**Comment by WainDing** [comment]
硬件纯解码，估计4-5路。如果加硬编码的话，应该支持不了。

**Comment by yuan631111976** [comment]
那如果只解码4路，然后再加一路编码，加上6路合成呢？需要把6路绘制成一路到Surface上面，然后再硬编码！

**Comment by HermanChen** [comment]
先试试纯解码，把内核的硬件时间打印出来看下。因为码流不同的话，区别也比较大。还有，Android 上的性能是会差一些，中间开销大

**Comment by yuan631111976** [comment]
嗯嗯，OK,那如果是linux是要好很多吗？

**Comment by HermanChen** [comment]
相对会好一些，也是要看硬件上限
