### ISSUE TITLE
mpp 和 vpu 编码有什么区别，如何确保硬件编码

### ISSUE THREAD

**Issue by logic-basic** [rockchip-linux/mpp#97]
我使用的是rv1108芯片。
目前使用的是mpp进行编码，发现libmpp库没有链接libvpu库。libvpu有链接libmpp库。
发现在test里也可以使用vpu进行编码。

1、那vpu和mpp的编码区别是什么呢。
2、如何保证我现在使用的是硬件编码，又怎样操作，可以切换到软件编码呢。

**Comment by HermanChen** [comment]
libvpu.so 库是用来与 librk_vpuapi.so 配合进行前向兼容，支持旧的 API。
现在推荐使用 mpp 库处理，默认就是硬编码，mpp 里没有软件编码实现

**Comment by logic-basic** [comment]
感谢

**Comment by HermanChen** [comment]
不客气 : )
